import type { HistoryChapter, HistoryScene } from "@/types/game";

export const historyChapters: HistoryChapter[] = [
  {
    id: "capitulo-1",
    part: 1,
    title: "Tratado e promessa",
    summary: "A disputa pelo Acre vira decisao diplomatica e promessa ferroviaria.",
    status: "available",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Contexto historico documentado; as falas do jogo dramatizam pontos de vista plausiveis.",
    unlockSource: "history.capitulo-1",
  },
  {
    id: "capitulo-2",
    part: 2,
    title: "Entrar na mata",
    summary: "Acampamentos, logistica e o choque humano da abertura do tracado.",
    status: "available",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Contexto historico documentado; a camada decisoria funciona como dramatizacao guiada.",
    unlockSource: "history.capitulo-2",
  },
  {
    id: "capitulo-3",
    part: 3,
    title: "Doenca, hospital e sobrevivencia",
    summary: "O colapso da \"Ferrovia do Diabo\" e a intervencao vital de Oswaldo Cruz (1910).",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Planejado como expansao baseada em fontes historicas documentadas.",
    unlockSource: "history.capitulo-3",
  },
  {
    id: "capitulo-4",
    part: 4,
    title: "Engenharia e colapso da borracha",
    summary: "A inauguracao dos 366km e a imediata ruina economica causada pela concorrencia asiatica em 1913.",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejado como expansao baseada em fontes historicas documentadas.",
    unlockSource: "history.capitulo-4",
  },
  {
    id: "capitulo-5",
    part: 5,
    title: "Guerra, Vargas e Soldados da Borracha",
    summary: "Da encampar do Estado ao novo derramamento de sangue amazonico para a Segunda Guerra (1943).",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejado como expansao baseada em fontes historicas documentadas.",
    unlockSource: "history.capitulo-5",
  },
  {
    id: "capitulo-6",
    part: 6,
    title: "Ruina, tombamento e reabertura",
    summary: "De 1972 ao renascimento turistico promovido pela Amazon Fort em 2024.",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "reopening-2024",
    confidenceNote: "Planejado como expansao baseada em fontes historicas e patrimoniais documentadas.",
    unlockSource: "history.capitulo-6",
  },
];

export const historyScenes: HistoryScene[] = [
  {
    id: "c1-s1",
    chapterId: "capitulo-1",
    title: "A compensacao ferroviaria",
    context: "Em 1903, o Acre vira território brasileiro sob pagamento de 2 milhões de libras e a obrigação de erguer a estrada de ferro.",
    dialogue: "\"Se a promessa for aceita, ela precisa parecer viavel desde o papel\", sussurra um assessor no gabinete.",
    characterId: "barao-rio-branco",
    locationId: "porto-velho",
    historicalAnchor: "Tratado de Petropolis e compensacao ferroviaria.",
    outcomeTags: ["diplomacia", "promessa", "territorio"],
    dramaticRole: "setup",
    choices: [
      {
        id: "c1-s1-a",
        label: "Destacar a ferrovia como pacto de Estado",
        consequence: "A promessa ganha peso politico e passa a organizar a narrativa publica da obra.",
        delta: { moral: 6, progresso: 4 },
      },
      {
        id: "c1-s1-b",
        label: "Tratar a ferrovia apenas como compensacao tecnica",
        consequence: "O acordo avanca, mas sem mobilizar a mesma nocao de projeto historico.",
        delta: { progresso: 5, moral: -2 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Fato historico documentado; a fala e a escolha dramatizam um debate plausivel de epoca.",
    unlockSource: "history.capitulo-1.scene-1",
  },
  {
    id: "c1-s2",
    chapterId: "capitulo-1",
    title: "Porto Velho como base da obra",
    context: "A implantacao do canteiro redefine a escala da ocupacao e da logistica local.",
    dialogue: "\"Nao estamos montando so um porto; estamos montando uma cidade de passagem e trabalho\", diz um chefe de operacoes.",
    characterId: "engenheira-amalia",
    locationId: "porto-velho",
    historicalAnchor: "Formacao urbana associada ao atendimento da obra.",
    outcomeTags: ["cidade", "logistica", "porto"],
    dramaticRole: "pressure",
    choices: [
      {
        id: "c1-s2-a",
        label: "Priorizar armazens, agua e enfermaria",
        consequence: "A base cresce com mais suporte para o trabalho, ainda que o cronograma aperte.",
        delta: { saude: 5, moral: 4, progresso: -3 },
      },
      {
        id: "c1-s2-b",
        label: "Priorizar ritmo de montagem do canteiro",
        consequence: "A operacao acelera, mas a estrutura de apoio fica mais fragil.",
        delta: { progresso: 6, saude: -4 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "porto-velho-formation",
    confidenceNote: "Contexto documentado; a decisao sintetiza tensoes plausiveis do arranque da obra.",
    unlockSource: "history.capitulo-1.scene-2",
  },
  {
    id: "c1-s3",
    chapterId: "capitulo-1",
    title: "Promessa publica e custo humano",
    context: "O discurso oficial projeta progresso, mas a floresta e a distancia ja cobram organizacao rigorosa.",
    dialogue: "\"Toda promessa feita em gabinete volta como cobranca no barranco\", avisa um tecnico recem-chegado.",
    characterId: "engenheira-amalia",
    locationId: "porto-velho",
    historicalAnchor: "Choque entre discurso de progresso e viabilidade amazônica.",
    outcomeTags: ["progresso", "pressao", "territorio"],
    dramaticRole: "decision",
    choices: [
      {
        id: "c1-s3-a",
        label: "Assumir publicamente as dificuldades logisticas",
        consequence: "A expectativa se ajusta, e a equipe passa a operar com menos fantasia triunfalista.",
        delta: { moral: 5, progresso: -2 },
      },
      {
        id: "c1-s3-b",
        label: "Sustentar a narrativa de velocidade total",
        consequence: "O impulso inicial cresce, mas a margem para erro fica menor.",
        delta: { progresso: 6, moral: -4 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Base historica documentada; a escolha traduz um conflito de narrativa plausivel.",
    unlockSource: "history.capitulo-1.scene-3",
  },
  {
    id: "c1-s4",
    chapterId: "capitulo-1",
    title: "Fecho da promessa",
    context: "A decisao politica esta tomada: agora a memoria da ferrovia dependera do modo como essa promessa entra na mata.",
    dialogue: "\"O tratado terminou no papel; a historia vai comecar no barro\", resume um observador da comissao.",
    characterId: "barao-rio-branco",
    locationId: "porto-velho",
    historicalAnchor: "Transicao entre diplomacia e abertura efetiva da obra.",
    outcomeTags: ["transicao", "memoria", "politica"],
    dramaticRole: "consequence",
    choices: [
      {
        id: "c1-s4-a",
        label: "Registrar os motivos da obra com clareza",
        consequence: "A memoria do acordo fica mais legivel para quem vai enfrentar a obra depois.",
        delta: { moral: 4, progresso: 2 },
      },
      {
        id: "c1-s4-b",
        label: "Encerrar o capitulo com discurso de conquista",
        consequence: "O efeito simbolico cresce, mas a complexidade historica fica mais escondida.",
        delta: { progresso: 4, moral: -3 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Contexto documentado; o fecho dramatiza o salto entre acordo diplomatico e obra material.",
    unlockSource: "history.capitulo-1.scene-4",
  },
  {
    id: "c2-s1",
    chapterId: "capitulo-2",
    title: "Primeiros acampamentos",
    context: "Após as fracassadas missões de Church e Collins, Percival Farquhar recruta 20 mil homens de 50 nacionalidades. A floresta hostil é agora a casa.",
    dialogue: "\"A mata nao recebe plano mal resolvido. Gregos ou Antilhanos, o perigo na foice é o mesmo\", adverte um operador de suprimentos.",
    characterId: "estivador-caribenho",
    locationId: "porto-velho",
    historicalAnchor: "Montagem de acampamentos e logistica inicial.",
    outcomeTags: ["acampamento", "suprimentos", "mata"],
    dramaticRole: "setup",
    choices: [
      {
        id: "c2-s1-a",
        label: "Montar base menor, mas mais protegida",
        consequence: "A equipe avanca com mais cautela e menos desgaste imediato.",
        delta: { saude: 5, moral: 3, progresso: -2 },
      },
      {
        id: "c2-s1-b",
        label: "Abrir frente ampla para ganhar ritmo",
        consequence: "O tracado comeca a render, mas a vida no acampamento fica mais exposta.",
        delta: { progresso: 6, saude: -4, moral: -2 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Base historica documentada; a escolha dramatiza a tensao entre ritmo e suporte no acampamento.",
    unlockSource: "history.capitulo-2.scene-1",
  },
  {
    id: "c2-s2",
    chapterId: "capitulo-2",
    title: "Fronteira de suprimentos",
    context: "Cada atraso de carga afeta ferramenta, comida, remedio e moral de forma encadeada.",
    dialogue: "\"Quando o suprimento falha, falha tambem a confianca\", comenta Tobias na beira do rio.",
    characterId: "tobias-candelaria",
    locationId: "candelaria",
    historicalAnchor: "Dependencia logistica intensa e vulneravel.",
    outcomeTags: ["suprimentos", "saude", "rotina"],
    dramaticRole: "pressure",
    choices: [
      {
        id: "c2-s2-a",
        label: "Racionar com transparencia e registro",
        consequence: "A perda e compartilhada, mas a equipe entende melhor o motivo do aperto.",
        delta: { moral: 4, saude: 3, progresso: -2 },
      },
      {
        id: "c2-s2-b",
        label: "Manter o ritmo e empurrar a crise para depois",
        consequence: "A frente nao para agora, embora a tensao cresca nos bastidores.",
        delta: { progresso: 5, moral: -4, saude: -3 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Contexto documentado; a escolha dramatiza um padrao plausivel de pressao logistica.",
    unlockSource: "history.capitulo-2.scene-2",
  },
  {
    id: "c2-s3",
    chapterId: "capitulo-2",
    title: "Choque ambiental e humano",
    context: "A mata deixa de ser pano de fundo e passa a comandar tempo, deslocamento e fadiga.",
    dialogue: "\"Nao e so distancia; e uma distancia que responde ao corpo\", diz Samuel ao final do turno.",
    characterId: "estivador-caribenho",
    locationId: "candelaria",
    historicalAnchor: "Choque ambiental e humano da abertura do tracado.",
    outcomeTags: ["fadiga", "ambiente", "trabalho"],
    dramaticRole: "decision",
    choices: [
      {
        id: "c2-s3-a",
        label: "Reduzir frente por um dia e reorganizar turnos",
        consequence: "O folego retorna parcialmente e a equipe entende que o territorio exige outro ritmo.",
        delta: { saude: 6, moral: 4, progresso: -3 },
      },
      {
        id: "c2-s3-b",
        label: "Segurar o turno integral para nao perder terreno",
        consequence: "O avanco continua, mas o desgaste fisico se torna mais visivel.",
        delta: { progresso: 6, saude: -5, moral: -3 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Fato documentado; a camada decisoria dramatiza o impacto corporal do tracado.",
    unlockSource: "history.capitulo-2.scene-3",
  },
  {
    id: "c2-s4",
    chapterId: "capitulo-2",
    title: "Memoria do canteiro",
    context: "No fim da abertura inicial, o canteiro ja guarda marcas que vao alem do progresso medido em quilometros.",
    dialogue: "\"A obra anda, mas cada passo deixa lembranca em quem ficou\", resume Tobias.",
    characterId: "tobias-candelaria",
    locationId: "candelaria",
    historicalAnchor: "Formacao de memoria de trabalho e sofrimento ligada ao canteiro.",
    outcomeTags: ["memoria", "canteiro", "trabalho"],
    dramaticRole: "consequence",
    choices: [
      {
        id: "c2-s4-a",
        label: "Registrar perdas, rotinas e nomes",
        consequence: "A memoria do canteiro ganha espessura e se aproxima do que hoje se preserva.",
        delta: { moral: 5, saude: 2, progresso: 1 },
      },
      {
        id: "c2-s4-b",
        label: "Fechar o capitulo apenas pelo ritmo alcancado",
        consequence: "O feito tecnico fica em destaque, mas o custo humano sai da moldura.",
        delta: { progresso: 4, moral: -4 },
      },
    ],
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Base documental ligada a memoria sanitaria e humana da obra; a fala e dramatizada.",
    unlockSource: "history.capitulo-2.scene-4",
  },
];

export const historyChapterById = Object.fromEntries(historyChapters.map((item) => [item.id, item])) as Record<string, HistoryChapter>;

export const historyScenesByChapterId = historyChapters.reduce<Record<string, HistoryScene[]>>((acc, chapter) => {
  acc[chapter.id] = historyScenes.filter((scene) => scene.chapterId === chapter.id);
  return acc;
}, {});
