import type { MuseumArea, MuseumEntry } from "@/types/game";

export const museumAreas: MuseumArea[] = [
  {
    id: "area-diplomacia",
    title: "Diplomacia",
    icon: "scroll-text",
    unlockThreshold: 1,
    entryIds: ["museu-tratado", "museu-porto-velho", "museu-diplomacia-fronteira"],
    status: "available",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Ala apoiada em fatos diplomaticos documentados.",
    unlockSource: "museum.area.diplomacia",
  },
  {
    id: "area-locomotivas",
    title: "Locomotivas",
    icon: "train-front",
    unlockThreshold: 1,
    entryIds: ["museu-locomotiva-18", "museu-litorina", "museu-oficina-aberta"],
    status: "available",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Ala apoiada em uso contemporaneo documentado do acervo rodante.",
    unlockSource: "museum.area.locomotivas",
  },
  {
    id: "area-candelaria",
    title: "Hospital e Candelaria",
    icon: "cross",
    unlockThreshold: 1,
    entryIds: ["museu-candelaria", "museu-quinino", "museu-memoria-trabalho"],
    status: "available",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Ala apoiada em fatos historicos documentados sobre saude e memoria da obra.",
    unlockSource: "museum.area.candelaria",
  },
  {
    id: "area-construcao",
    title: "Construcao",
    icon: "hammer",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.construcao",
  },
  {
    id: "area-trilhos",
    title: "Trilhos e pontes",
    icon: "route",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.trilhos",
  },
  {
    id: "area-trabalhadores",
    title: "Trabalhadores e cotidiano",
    icon: "users",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.trabalhadores",
  },
  {
    id: "area-borracha",
    title: "Borracha e circulacao",
    icon: "package",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.borracha",
  },
  {
    id: "area-ruina",
    title: "Ruina e preservacao",
    icon: "archive",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "iphan-2008",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.ruina",
  },
  {
    id: "area-reabertura",
    title: "Reabertura e turismo",
    icon: "map",
    unlockThreshold: 2,
    entryIds: [],
    status: "planned",
    contentType: "contemporary_fact",
    sourceRef: "reopening-2024",
    confidenceNote: "Planejada para expansao futura.",
    unlockSource: "museum.area.reabertura",
  },
];

export const museumEntries: MuseumEntry[] = [
  {
    id: "museu-tratado",
    areaId: "area-diplomacia",
    title: "Tratado de Petropolis",
    summary: "Documento de origem da promessa ferroviaria.",
    whatIsIt: "Acordo diplomatico de 1903 ligado ao destino do Acre e a compensacao ferroviaria.",
    historicalUse: "Serviu de marco politico para a incorporacao do Acre e para o compromisso de construir a estrada de ferro.",
    whereAppearsInGame: "Hub, Historia Interativa e modulo de Diplomacia do quiz.",
    whyItMattersToday: "Ajuda o jogador a ler a EFMM como patrimonio geopolitico, nao apenas como objeto cenico.",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Fato historico documentado.",
    unlockSource: "quiz.question.qd-01",
  },
  {
    id: "museu-porto-velho",
    areaId: "area-diplomacia",
    title: "Vila Americana",
    summary: "Farquhar, 50 nacionalidades e a segregação de Porto Velho.",
    whatIsIt: "Leitura urbana da cidade, marcada pela 'Vila Americana' (eletricidade, Marconi, quadras de tênis) separada dos trabalhadores pela Avenida Divisória.",
    historicalUse: "Funcionou como base logistica central e segregada da obra da EFMM.",
    whereAppearsInGame: "Historia Interativa, timeline do hub e quiz de Diplomacia.",
    whyItMattersToday: "Conecta patrimonio ferroviario e a origem da estratificação urbana de Rondonia.",
    contentType: "historical_fact",
    sourceRef: "porto-velho-formation",
    confidenceNote: "Fato historico documentado.",
    unlockSource: "quiz.question.qd-04",
  },
  {
    id: "museu-diplomacia-fronteira",
    areaId: "area-diplomacia",
    title: "Diplomacia e fronteira",
    summary: "A EFMM nasceu de disputa territorial e compromisso interestatal.",
    whatIsIt: "Chave interpretativa que liga diplomacia, territorio e logistica.",
    historicalUse: "Explica a ferrovia como resposta politica a um arranjo regional.",
    whereAppearsInGame: "Hub, quiz e cenas do capitulo 1.",
    whyItMattersToday: "Evita reduzir a ferrovia a nostalgia sem contexto.",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Fato historico documentado.",
    unlockSource: "quiz.question.qd-07",
  },
  {
    id: "museu-locomotiva-18",
    areaId: "area-locomotivas",
    title: "Locomotiva 18",
    summary: "Peca simbolica do programa de Restauração 2026.",
    whatIsIt: "Locomotiva exibida como eixo de leitura tecnica e patrimonial do complexo.",
    historicalUse: "Representa a memoria material da operacao ferroviaria e do acervo preservado.",
    whereAppearsInGame: "Restauração 2026, hub e quiz de Construcao.",
    whyItMattersToday: "Mostra como o patrimonio pode ser ativado sem esconder sua fragilidade material.",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Situacao contemporanea documentada.",
    unlockSource: "quiz.question.qc-05",
  },
  {
    id: "museu-locomotiva-50",
    areaId: "area-locomotivas",
    title: "Locomotiva 50",
    summary: "Restauração integral visando o futuro tracionamento de passageiros.",
    whatIsIt: "Máquina enviada a Santa Catarina para refazimento completo de caldeira rodante, com base da ABPF e IPHAN.",
    historicalUse: "Ferramenta pesada nas décadas douradas do império ferroviário antes das BR-364.",
    whereAppearsInGame: "Status de Hoje no Complexo e timeline 2026.",
    whyItMattersToday: "Representa o resgate mecânico ativo do patrimônio em transição pós-2024.",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Ação de restauro documentada (2025/2026).",
    unlockSource: "museum.area.locomotivas",
  },
  {
    id: "museu-litorina",
    areaId: "area-locomotivas",
    title: "Litorina",
    summary: "Passeio e memoria se encontram no material rodante contemporaneo do complexo.",
    whatIsIt: "Material rodante ligado a passeios e mediacao publica do patrimonio.",
    historicalUse: "No contexto atual, ajuda a traduzir deslocamento, tecnica e visita mediada.",
    whereAppearsInGame: "Restauração 2026 e bloco 'Hoje no complexo'.",
    whyItMattersToday: "Legitima a ideia de patrimonio vivo e experiencia publica do conjunto.",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Situacao contemporanea documentada.",
    unlockSource: "quiz.question.qc-09",
  },
  {
    id: "museu-oficina-aberta",
    areaId: "area-locomotivas",
    title: "Oficina aberta",
    summary: "Restauro visivel como pedagogia do patrimonio.",
    whatIsIt: "Conceito curatorial que torna o processo de conservacao parte da experiencia do visitante.",
    historicalUse: "No jogo, mostra bastidor tecnico de locomotiva e litorina.",
    whereAppearsInGame: "Modulo Material Rodante na Restauração 2026.",
    whyItMattersToday: "Aproxima o publico da manutencao e amplia a confianca no trabalho patrimonial.",
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de estrategia curatorial para 2026.",
    unlockSource: "restoration.choice.rod-restauro-a",
  },
  {
    id: "museu-candelaria",
    areaId: "area-candelaria",
    title: "Hospital e Cemiterio da Candelaria",
    summary: "Memoria sanitaria incontornavel da construcao.",
    whatIsIt: "Conjunto memorial associado a doenca, cuidado e luto na obra da EFMM, com mais de 1.500 mortes oficiais locais.",
    historicalUse: "Operou como referencia de enfrentamento de surtos e de registro de mortes na 'Ferrovia do Diabo'.",
    whereAppearsInGame: "Historia Interativa, quiz de Construcao e ala do museu.",
    whyItMattersToday: "Impede que a historia da ferrovia seja contada sem corpo, trabalho e a trágica perda humana (6 mil a 10 mil vidas).",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Fatos historicos em torno das estátisticas aceitas.",
    unlockSource: "quiz.question.qc-03",
  },
  {
    id: "museu-oswaldo-cruz",
    areaId: "area-candelaria",
    title: "Sanitarista Oswaldo Cruz",
    summary: "Intervenção sistemática em 1910 para contornar a letalidade por Malária.",
    whatIsIt: "Plano sanitarista usando telas metálicas finas para barrar os mosquitos e obrigação do quinino no canteiro.",
    historicalUse: "Diminuiu drasticamente a taxa de letalidade entre milhares de braçais da EFMM.",
    whereAppearsInGame: "Timeline Histórica e Arquivos do Museu.",
    whyItMattersToday: "Evidencia que infraestrutura bruta na Amazônia não prosperou sem a ciência biomédica de fronteira.",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Fato histórico de 1910 registrado e documentado.",
    unlockSource: "museum.area.candelaria",
  },
  {
    id: "museu-quinino",
    areaId: "area-candelaria",
    title: "Quinino e triagem",
    summary: "Decisao medica tambem era decisao moral e politica.",
    whatIsIt: "Leitura do quinino como recurso escasso em cenarios de alta vulnerabilidade.",
    historicalUse: "A falta de recursos de cuidado exigia criterios de prioridade no canteiro.",
    whereAppearsInGame: "Historia Interativa, especialmente no arco de saude e sobrevivencia.",
    whyItMattersToday: "Traduz em linguagem jogavel o custo etico das escolhas sobre cuidado.",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Fato historico documentado com dramatizacao controlada na interface.",
    unlockSource: "history.choice.c2-s2-a",
  },
  {
    id: "museu-memoria-trabalho",
    areaId: "area-candelaria",
    title: "Memoria do trabalho",
    summary: "O canteiro deixa marcas que nao cabem so em progresso tecnico.",
    whatIsIt: "Entrada dedicada a nomes, perdas e ritmos do trabalho na floresta.",
    historicalUse: "Ajuda a ligar cotidiano, fadiga e memoria da obra.",
    whereAppearsInGame: "Fecho do capitulo 2 e resultado integrado.",
    whyItMattersToday: "Reforca a ideia de patrimonio humano, nao apenas industrial.",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Fato historico documentado com organizacao curatorial do jogo.",
    unlockSource: "history.choice.c2-s4-a",
  },
];

export const museumAreaById = Object.fromEntries(museumAreas.map((item) => [item.id, item])) as Record<string, MuseumArea>;
export const museumEntryById = Object.fromEntries(museumEntries.map((item) => [item.id, item])) as Record<string, MuseumEntry>;
