import { type NarrativeScene } from "@/types/game";

export const narrativeScenes: NarrativeScene[] = [
  {
    id: "n-01",
    chapter: 2,
    title: "Madrugada em Jaci-Parana",
    protagonist: "medico",
    text: "O enfermeiro Tobias bate na porta. Dezessete homens com febre alta e calafrios. Reed exige turno normal ate a tarde.",
    choices: [
      {
        id: "n-01-a",
        label: "Isolar os doentes imediatamente",
        consequence: "Voce segura a autoridade medica. O contágio desacelera, mas o canteiro perde metade da forca.",
        delta: { saude: 20, progresso: -20, moral: 5 },
        setFlags: ["isolated_sick"],
        unlocks: ["codex-hospital-candelaria"],
      },
      {
        id: "n-01-b",
        label: "Negociar meio turno com Reed",
        consequence: "Dois homens desmaiam no trilho antes do meio-dia. O boato atravessa o acampamento.",
        delta: { saude: -10, progresso: -5, moral: -5 },
      },
      {
        id: "n-01-c",
        label: "Ceder decisao ao capataz",
        consequence: "Sua autoridade medica desaba. Muitos deixam de relatar sintomas por medo.",
        delta: { saude: -20, progresso: 5, moral: -10 },
        latentDelta: { saude: -8, moral: -4 },
      },
    ],
  },
  {
    id: "n-02",
    chapter: 2,
    title: "Setor 7",
    protagonist: "ambos",
    text: "Barbadianos recusam entrada no setor. Brathwaite fala em terra de espiritos; Reed ameaça desconto coletivo.",
    choices: [
      {
        id: "n-02-a",
        label: "Apoiar Brathwaite e negociar rota alternativa",
        consequence: "A equipe recupera confiança. O custo de prazo aparece imediatamente.",
        delta: { moral: 20, progresso: -25 },
        requiredFlags: ["isolated_sick"],
        setFlags: ["barbadian_alliance"],
        unlocks: ["codex-brathwaite"],
      },
      {
        id: "n-02-b",
        label: "Ficar neutro e manter engenharia no comando",
        consequence: "Reed força entrada. Pedidos de demissao surgem no fim do turno.",
        delta: { moral: -10 },
        requiredFlags: ["isolated_sick"],
      },
      {
        id: "n-02-c",
        label: "Priorizar os casos graves com quinino escasso",
        consequence: "A triagem salva vidas, mas o ritmo da obra cai.",
        delta: { saude: 15, moral: 10, progresso: -20 },
      },
      {
        id: "n-02-d",
        label: "Tratar primeiro os mais produtivos",
        consequence: "A revolta explode no acampamento quando a prioridade vaza.",
        delta: { saude: -5, moral: -20, progresso: 10 },
      },
    ],
  },
  {
    id: "n-03",
    chapter: 2,
    title: "Carta de Barbados",
    protagonist: "barbadiano",
    text: "Chega uma carta de familiares denunciando jornadas desumanas. A equipe exige uma resposta publica.",
    choices: [
      {
        id: "n-03-a",
        label: "Ler a carta em assembleia",
        consequence: "A dor vira memoria coletiva e pacto de cuidado.",
        delta: { moral: 12, progresso: -5 },
        setFlags: ["public_memory"],
      },
      {
        id: "n-03-b",
        label: "Resolver internamente sem exposicao",
        consequence: "Evita ruído imediato, mas amplia desconfianca entre turnos.",
        delta: { progresso: 4, moral: -8 },
        latentDelta: { moral: -6 },
      },
    ],
  },
  {
    id: "n-04",
    chapter: 2,
    title: "Agua Parada",
    protagonist: "medico",
    text: "A chuva transformou o entorno dos alojamentos em foco de mosquito. Falta pessoal para drenagem.",
    choices: [
      {
        id: "n-04-a",
        label: "Parar frente de trilhos por 24h para saneamento",
        consequence: "A drenagem reduz o risco sanitário e preserva a equipe.",
        delta: { saude: 14, progresso: -10, moral: 4 },
      },
      {
        id: "n-04-b",
        label: "Aplicar resposta parcial sem parar obras",
        consequence: "A crise não explode agora, mas segue latente na semana seguinte.",
        delta: { progresso: 6, saude: -6 },
        latentDelta: { saude: -8 },
      },
    ],
  },
  {
    id: "n-05",
    chapter: 2,
    title: "Comissao de Engenheiros",
    protagonist: "ambos",
    text: "Uma comissão externa exige resultado no cronograma final do km 88, ignorando custos humanos.",
    choices: [
      {
        id: "n-05-a",
        label: "Defender protocolo sanitario e ritmo seguro",
        consequence: "Voce preserva vidas e assume desgaste politico.",
        delta: { saude: 10, moral: 8, progresso: -8 },
      },
      {
        id: "n-05-b",
        label: "Aceitar meta extrema por 72h",
        consequence: "O avanço impressiona, mas aumenta risco de colapso.",
        delta: { progresso: 14, moral: -10, saude: -10 },
      },
    ],
  },
  {
    id: "n-06",
    chapter: 2,
    title: "Noite no Hospital Candelaria",
    protagonist: "medico",
    text: "Faltam leitos e o estoque de quinino cai. Tobias pede decisão de prioridade.",
    choices: [
      {
        id: "n-06-a",
        label: "Priorizar risco de morte",
        consequence: "A decisão reforça ética médica e confiança da enfermaria.",
        delta: { saude: 12, moral: 6, progresso: -4 },
        unlocks: ["codex-protocolo-quinino"],
      },
      {
        id: "n-06-b",
        label: "Priorizar retorno ao trabalho",
        consequence: "A obra acelera, mas o acampamento se divide moralmente.",
        delta: { progresso: 10, moral: -12, saude: -6 },
      },
    ],
  },
  {
    id: "n-07",
    chapter: 2,
    title: "Km Maldito",
    protagonist: "barbadiano",
    text: "Rumores sobre o 'km maldito' espalham medo. Sem resposta simbólica, o turno B pode parar.",
    choices: [
      {
        id: "n-07-a",
        label: "Erguer memorial provisório aos mortos",
        consequence: "Memoria e luto reduzem tensão e restauram coesão.",
        delta: { moral: 14, progresso: -6, saude: 4 },
        setFlags: ["memorial_raised"],
        unlocks: ["codex-km-maldito"],
      },
      {
        id: "n-07-b",
        label: "Reprimir rumores e manter marcha",
        consequence: "O medo vira silêncio, depois revolta.",
        delta: { progresso: 8, moral: -12 },
        latentDelta: { moral: -8, saude: -4 },
      },
    ],
  },
  {
    id: "n-08",
    chapter: 2,
    title: "Fecho do Capitulo",
    protagonist: "ambos",
    text: "O surto recua, mas o custo humano e politico fica gravado. Sua liderança agora será lembrada.",
    choices: [
      {
        id: "n-08-a",
        label: "Concluir com relatorio transparente",
        consequence: "A verdade protege a memoria coletiva e prepara o próximo conflito.",
        delta: { moral: 6, progresso: -2, saude: 4 },
      },
      {
        id: "n-08-b",
        label: "Concluir com discurso triunfalista",
        consequence: "A narrativa oficial ganha brilho, mas perde credibilidade entre operarios.",
        delta: { progresso: 5, moral: -8 },
      },
    ],
  },
];
