import type { QuizModule, QuizQuestion } from "@/types/game";

export const quizModules: QuizModule[] = [
  {
    id: "quiz-diplomacia",
    title: "Diplomacia e territorio",
    summary: "Acre, Tratado de Petropolis e funcao geopolitica da ferrovia.",
    status: "available",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Perguntas baseadas em marco diplomatico documentado.",
    unlockSource: "quiz.module.1",
  },
  {
    id: "quiz-construcao",
    title: "Construcao e engenharia",
    summary: "Trajeto, desafios tecnicos, oficina e material rodante.",
    status: "available",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Perguntas baseadas em fatos documentados da construcao da ferrovia.",
    unlockSource: "quiz.module.2",
  },
  {
    id: "quiz-trabalho",
    title: "Trabalho, saude e vida cotidiana",
    summary: "Modulo planejado para expansao futura.",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Planejado como expansao de conteudo.",
    unlockSource: "quiz.module.3",
  },
  {
    id: "quiz-economia",
    title: "Economia, operacao e declinio",
    summary: "Modulo planejado para expansao futura.",
    status: "planned",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Planejado como expansao de conteudo.",
    unlockSource: "quiz.module.4",
  },
  {
    id: "quiz-patrimonio",
    title: "Patrimonio, museu e atualidade",
    summary: "Modulo planejado para expansao futura.",
    status: "planned",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Planejado como expansao de conteudo com base contemporanea documentada.",
    unlockSource: "quiz.module.5",
  },
];

export const quizQuestions: QuizQuestion[] = [
  {
    id: "qd-01",
    moduleId: "quiz-diplomacia",
    prompt: "Qual tratado de 1903 esta diretamente ligado a origem geopolitica da EFMM?",
    options: ["Tratado de Petropolis", "Tratado de Madrid", "Tratado de Ayacucho", "Tratado de Assuncao"],
    correctIndex: 0,
    explanation: "O Tratado de Petropolis, de 1903, esta no centro da origem diplomatica da ferrovia.",
    difficulty: "easy",
    topic: "tratado",
    museumUnlockId: "museu-tratado",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qd-01",
  },
  {
    id: "qd-02",
    moduleId: "quiz-diplomacia",
    prompt: "A promessa ferroviaria surgiu como compensacao em negociacao envolvendo o Acre e qual pais?",
    options: ["Bolivia", "Peru", "Chile", "Argentina"],
    correctIndex: 0,
    explanation: "A negociacao central do tratado envolveu Brasil e Bolivia.",
    difficulty: "easy",
    topic: "fronteira",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qd-02",
  },
  {
    id: "qd-03",
    moduleId: "quiz-diplomacia",
    prompt: "Na leitura do jogo, a ferrovia aparece como elo entre diplomacia e qual necessidade regional?",
    options: ["Integracao logistica", "Corrida do ouro", "Defesa costeira", "Expansao industrial paulista"],
    correctIndex: 0,
    explanation: "A obra e apresentada como instrumento de integracao logistica ligado ao acordo diplomatico.",
    difficulty: "medium",
    topic: "logistica",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada em interpretacao historica coerente com o tratado.",
    unlockSource: "quiz.question.qd-03",
  },
  {
    id: "qd-04",
    moduleId: "quiz-diplomacia",
    prompt: "Qual cidade se consolidou diretamente para atender a construcao da ferrovia?",
    options: ["Porto Velho", "Santarem", "Boa Vista", "Maraba"],
    correctIndex: 0,
    explanation: "Porto Velho se estruturou para atender a obra e a operacao associada a ferrovia.",
    difficulty: "easy",
    topic: "urbanizacao",
    museumUnlockId: "museu-porto-velho",
    contentType: "historical_fact",
    sourceRef: "porto-velho-formation",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qd-04",
  },
  {
    id: "qd-05",
    moduleId: "quiz-diplomacia",
    prompt: "Por que a timeline do produto inclui 1903 antes de 1907?",
    options: [
      "Porque a origem politica antecede a obra material",
      "Porque os trilhos ja estavam prontos em 1903",
      "Porque o tombamento ocorreu antes da construcao",
      "Porque o museu ja funcionava nesse ano",
    ],
    correctIndex: 0,
    explanation: "O jogo conecta a decisao politica de 1903 ao inicio das obras em 1907.",
    difficulty: "medium",
    topic: "timeline",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada em conexao historica documentada.",
    unlockSource: "quiz.question.qd-05",
  },
  {
    id: "qd-06",
    moduleId: "quiz-diplomacia",
    prompt: "Qual leitura o jogo privilegia sobre o tratado?",
    options: [
      "Diplomacia ligada a trabalho, territorio e memoria",
      "Somente uma lista de datas",
      "Apenas a biografia de um diplomata",
      "Somente a descricao tecnica da caldeira",
    ],
    correctIndex: 0,
    explanation: "A experiencia usa o tratado como ponto de partida para discutir territorio, trabalho e memoria.",
    difficulty: "medium",
    topic: "leitura critica",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada na proposta editorial do produto.",
    unlockSource: "quiz.question.qd-06",
  },
  {
    id: "qd-07",
    moduleId: "quiz-diplomacia",
    prompt: "Qual eixo do Museu Vivo conversa primeiro com esse modulo do quiz?",
    options: ["Diplomacia", "Pontes", "Hospital", "Ruina e preservacao"],
    correctIndex: 0,
    explanation: "O modulo de diplomacia abre entradas do museu ligadas ao tratado e a formacao de Porto Velho.",
    difficulty: "easy",
    topic: "museu",
    museumUnlockId: "museu-diplomacia-fronteira",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta ancorada na arquitetura do produto.",
    unlockSource: "quiz.question.qd-07",
  },
  {
    id: "qd-08",
    moduleId: "quiz-diplomacia",
    prompt: "A expressao 'ferrovia estrategica da borracha' liga a EFMM a qual camada maior?",
    options: ["Geopolitica regional e circulacao economica", "Turismo de praia", "Mineracao costeira", "Aviacao militar"],
    correctIndex: 0,
    explanation: "A leitura une diplomacia, economia e circulacao regional.",
    difficulty: "hard",
    topic: "geopolitica",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada em interpretacao historica coerente com a origem da ferrovia.",
    unlockSource: "quiz.question.qd-08",
  },
  {
    id: "qd-09",
    moduleId: "quiz-diplomacia",
    prompt: "Na proposta do jogo, por que 2008 e 2024 aparecem na mesma linha do tempo de 1903 e 1912?",
    options: [
      "Porque patrimonio vivo conecta origem, tombamento e reuso",
      "Porque todos os anos pertencem a fase de obra",
      "Porque a ferrovia nunca saiu de operacao plena",
      "Porque o tratado foi refeito em 2024",
    ],
    correctIndex: 0,
    explanation: "A timeline do hub costura origem diplomatica, memoria patrimonial e reabertura contemporanea.",
    difficulty: "medium",
    topic: "patrimonio vivo",
    contentType: "historical_fact",
    sourceRef: "iphan-2008",
    confidenceNote: "Pergunta baseada na articulacao editorial do produto.",
    unlockSource: "quiz.question.qd-09",
  },
  {
    id: "qd-10",
    moduleId: "quiz-diplomacia",
    prompt: "Qual frase resume melhor o modulo 'Diplomacia e territorio'?",
    options: [
      "A origem da EFMM e politica antes de virar trilho",
      "A EFMM nasceu apenas como museu urbano",
      "A ferrovia foi criada para corridas esportivas",
      "O tratado tratava apenas de turismo contemporaneo",
    ],
    correctIndex: 0,
    explanation: "Esse modulo destaca a origem politica da ferrovia antes da fase material da construcao.",
    difficulty: "easy",
    topic: "sintese",
    contentType: "historical_fact",
    sourceRef: "treaty-1903",
    confidenceNote: "Pergunta baseada na sintese editorial do modulo.",
    unlockSource: "quiz.question.qd-10",
  },
  {
    id: "qc-01",
    moduleId: "quiz-construcao",
    prompt: "Em que intervalo historico a construcao da EFMM ocorreu?",
    options: ["1907-1912", "1890-1895", "1915-1920", "1930-1935"],
    correctIndex: 0,
    explanation: "A construcao da ferrovia se deu entre 1907 e 1912.",
    difficulty: "easy",
    topic: "cronologia",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qc-01",
  },
  {
    id: "qc-02",
    moduleId: "quiz-construcao",
    prompt: "Quais cidades a EFMM ligava historicamente?",
    options: ["Porto Velho e Guajara-Mirim", "Manaus e Belem", "Rio Branco e Cuiaba", "Macapa e Santarem"],
    correctIndex: 0,
    explanation: "A ferrovia ligava Porto Velho a Guajara-Mirim.",
    difficulty: "easy",
    topic: "trajeto",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qc-02",
  },
  {
    id: "qc-03",
    moduleId: "quiz-construcao",
    prompt: "Qual problema aparece como desafio recorrente na construcao e na narrativa do jogo?",
    options: ["Doencas tropicais e ambiente hostil", "Nevascas frequentes", "Escassez de rios", "Congestionamento urbano"],
    correctIndex: 0,
    explanation: "Doencas tropicais e ambiente hostil atravessam a experiencia historica da obra.",
    difficulty: "easy",
    topic: "ambiente",
    museumUnlockId: "museu-candelaria",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Pergunta baseada em fato historico documentado.",
    unlockSource: "quiz.question.qc-03",
  },
  {
    id: "qc-04",
    moduleId: "quiz-construcao",
    prompt: "No reposicionamento do produto, a Historia Interativa evita qual erro editorial?",
    options: [
      "Transformar sofrimento em espetaculo",
      "Mostrar cronologia",
      "Usar contexto documentado",
      "Conectar escolhas a barras",
    ],
    correctIndex: 0,
    explanation: "A tensao deve vir da decisao e do custo, nao do sensacionalismo.",
    difficulty: "medium",
    topic: "editorial",
    contentType: "historical_fact",
    sourceRef: "candelaria",
    confidenceNote: "Pergunta baseada na regra editorial do produto.",
    unlockSource: "quiz.question.qc-04",
  },
  {
    id: "qc-05",
    moduleId: "quiz-construcao",
    prompt: "Qual peca do acervo contemporaneo e usada no jogo como ativo simbolico de restauro?",
    options: ["Locomotiva 18", "Bondinho 3", "Vagao postal costeiro", "Guindaste naval"],
    correctIndex: 0,
    explanation: "A Locomotiva 18 e o eixo simbolico do modulo de material rodante na Entrega 1.",
    difficulty: "easy",
    topic: "material rodante",
    museumUnlockId: "museu-locomotiva-18",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Pergunta baseada em informacao contemporanea documentada.",
    unlockSource: "quiz.question.qc-05",
  },
  {
    id: "qc-06",
    moduleId: "quiz-construcao",
    prompt: "Qual abordagem o modulo Restauração 2026 assume sobre o presente do complexo?",
    options: [
      "Simulacao plausivel sobre base real documentada",
      "Reconstrucao literal de uma operacao plena ja existente",
      "Fantasia sem lastro documental",
      "Simulador ferroviario de 366 km em escala real",
    ],
    correctIndex: 0,
    explanation: "A camada de jogo explicita a simulacao de 2026 sem fingir que toda a operacao ja existe em escala plena.",
    difficulty: "medium",
    topic: "simulation_2026",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Pergunta baseada na regra editorial do produto.",
    unlockSource: "quiz.question.qc-06",
  },
  {
    id: "qc-07",
    moduleId: "quiz-construcao",
    prompt: "Qual destes elementos pertence ao modulo 'Trilhos' na Entrega 1?",
    options: ["Drenagem e seguranca de circulacao", "Catalogacao de retratos", "Campanha diplomatica", "Ranking local do quiz"],
    correctIndex: 0,
    explanation: "O modulo Trilhos inclui alinhamento, lastro, drenagem e seguranca de circulacao.",
    difficulty: "medium",
    topic: "modulos",
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Pergunta baseada no desenho do produto.",
    unlockSource: "quiz.question.qc-07",
  },
  {
    id: "qc-08",
    moduleId: "quiz-construcao",
    prompt: "No jogo, por que barracoes e galpoes entram no mesmo programa de restauro?",
    options: [
      "Porque sustentam museu, educacao e operacao publica",
      "Porque substituem o tratado de 1903",
      "Porque sao usados como locomotivas",
      "Porque eliminam a necessidade de visitacao",
    ],
    correctIndex: 0,
    explanation: "Eles sao tratados como infraestrutura de reuso patrimonial e educativo.",
    difficulty: "medium",
    topic: "reuso",
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Pergunta baseada no desenho contemporaneo do produto.",
    unlockSource: "quiz.question.qc-08",
  },
  {
    id: "qc-09",
    moduleId: "quiz-construcao",
    prompt: "Qual ponto do complexo ajuda a legitimar o Museu Vivo como payoff do jogo?",
    options: [
      "O complexo atual opera com museu e programacao de visitacao",
      "A inexistencia de acervo material",
      "O fechamento permanente desde 1912",
      "A substituicao dos trilhos por rodovia",
    ],
    correctIndex: 0,
    explanation: "A existencia de museu e agenda de visitacao sustenta o eixo de Museu Vivo no produto.",
    difficulty: "hard",
    topic: "museu vivo",
    museumUnlockId: "museu-litorina",
    contentType: "contemporary_fact",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Pergunta baseada em informacao contemporanea documentada fornecida ao projeto.",
    unlockSource: "quiz.question.qc-09",
  },
  {
    id: "qc-10",
    moduleId: "quiz-construcao",
    prompt: "Qual frase resume melhor o modulo 'Construcao e engenharia'?",
    options: [
      "Construir a EFMM foi um problema de territorio, tecnica e corpo",
      "Construir a EFMM foi apenas montar pecas em oficina urbana",
      "A engenharia ocorreu sem custo humano relevante",
      "A obra atual de 2026 substitui totalmente a memoria historica",
    ],
    correctIndex: 0,
    explanation: "O modulo articula tecnica, territorio e custo humano como parte da mesma historia.",
    difficulty: "medium",
    topic: "sintese",
    contentType: "historical_fact",
    sourceRef: "construction-1907-1912",
    confidenceNote: "Pergunta baseada na sintese editorial do produto.",
    unlockSource: "quiz.question.qc-10",
  },
];

export const quizModuleById = Object.fromEntries(quizModules.map((item) => [item.id, item])) as Record<string, QuizModule>;

export const quizQuestionsByModuleId = quizModules.reduce<Record<string, QuizQuestion[]>>((acc, module) => {
  acc[module.id] = quizQuestions.filter((question) => question.moduleId === module.id);
  return acc;
}, {});
