import { type QuizQuestion } from "@/types/game";

export const quizQuestions: QuizQuestion[] = [
  {
    id: "q-01",
    category: "Tratado de Petropolis",
    prompt: "Qual acordo formalizou a incorporacao do Acre ao Brasil?",
    options: ["Tratado de Petropolis", "Tratado de Tordesilhas", "Acordo de Genebra", "Pacto de Manaus"],
    correctIndex: 0,
    explanation: "O Tratado de Petropolis (1903) redefiniu fronteiras e incluiu compensacoes a Bolivia.",
    rewardUnlockId: "codex-tratado-petropolis",
  },
  {
    id: "q-02",
    category: "Tratado de Petropolis",
    prompt: "Qual infraestrutura foi prevista como compensacao diplomatica no contexto do tratado?",
    options: ["Estrada de Ferro Madeira-Mamore", "Ponte Rio-Niteroi", "Rodovia Transamazonica", "Porto de Santos"],
    correctIndex: 0,
    explanation: "A ferrovia foi parte central da engenharia politica e comercial do periodo.",
  },
  {
    id: "q-03",
    category: "Construcao",
    prompt: "Qual era um dos maiores desafios fisicos da construcao da EFMM?",
    options: ["Clima e doencas tropicais", "Falta de trilhos de aco", "Ausencia total de rios", "Neve constante"],
    correctIndex: 0,
    explanation: "Floresta densa, umidade extrema e epidemias marcaram o canteiro.",
  },
  {
    id: "q-04",
    category: "Construcao",
    prompt: "A EFMM foi planejada para ligar principalmente quais pontos?",
    options: ["Porto Velho e Guajara-Mirim", "Manaus e Belem", "Rio Branco e Cuiaba", "Macapa e Santarem"],
    correctIndex: 0,
    explanation: "A ferrovia conectava o trecho navegavel entre Porto Velho e Guajara-Mirim.",
  },
  {
    id: "q-05",
    category: "Trabalhadores",
    prompt: "Trabalhadores de qual origem tiveram presenca marcante nos canteiros?",
    options: ["Barbados e Caribe", "Escandinavia", "Asia Central", "Oceania"],
    correctIndex: 0,
    explanation: "Muitos trabalhadores caribenhos, incluindo barbadianos, atuaram na obra.",
    rewardUnlockId: "codex-brathwaite",
  },
  {
    id: "q-06",
    category: "Trabalhadores",
    prompt: "A diversidade de origens no canteiro gerou qual desafio adicional?",
    options: ["Convivencia linguistica e cultural", "Falta total de oficio tecnico", "Inexistencia de liderancas", "Ausencia de contratos"],
    correctIndex: 0,
    explanation: "Havia tensoes e negociacoes entre grupos com idiomas e valores distintos.",
  },
  {
    id: "q-07",
    category: "Doencas e Saneamento",
    prompt: "Qual doenca marcou dramaticamente os canteiros da EFMM?",
    options: ["Malaria", "Varicela", "Sarampo", "Tuberculose bovina"],
    correctIndex: 0,
    explanation: "A malaria foi uma das maiores causas de adoecimento e morte durante a obra.",
  },
  {
    id: "q-08",
    category: "Doencas e Saneamento",
    prompt: "Uma resposta sanitaria eficaz dependia principalmente de:",
    options: ["Drenagem e controle de vetores", "Apenas isolamento social", "Troca de trilhos", "Vacina unica"],
    correctIndex: 0,
    explanation: "Sem controle ambiental, surtos se repetiam rapidamente.",
  },
  {
    id: "q-09",
    category: "Locomotivas",
    prompt: "No contexto de restauro, o que significa elevar o nivel de uma locomotiva?",
    options: ["Recuperar funcionalidade e autenticidade", "Trocar tudo por pecas novas", "Pintar com cor moderna", "Remover componentes originais"],
    correctIndex: 0,
    explanation: "Restaurar exige equilibrio entre operacao, seguranca e preservacao historica.",
  },
  {
    id: "q-10",
    category: "Locomotivas",
    prompt: "Qual ativo foi definido como prioritario na V1 do jogo?",
    options: ["Locomotiva 18", "Locomotiva 01", "Tram urbano", "Carro presidencial"],
    correctIndex: 0,
    explanation: "A Locomotiva 18 e um marco jogavel do modo restauracao.",
    rewardUnlockId: "codex-locomotiva-18",
  },
  {
    id: "q-11",
    category: "Patrimonio",
    prompt: "Preservacao patrimonial significa apenas conservar objetos?",
    options: ["Nao, inclui memoria social e contexto", "Sim, basta evitar ferrugem", "Nao, inclui apenas turismo", "Sim, se houver foto"],
    correctIndex: 0,
    explanation: "Patrimonio envolve objetos, arquivos, relatos e significados coletivos.",
  },
  {
    id: "q-12",
    category: "Patrimonio",
    prompt: "Um codex historico no jogo serve para:",
    options: ["Transformar progresso em memoria desbloqueavel", "Substituir totalmente o gameplay", "Ser apenas glossario decorativo", "Limitar escolhas"],
    correctIndex: 0,
    explanation: "No produto, codex integra retencao, narrativa e aprendizagem.",
  },
  {
    id: "q-13",
    category: "Construcao",
    prompt: "Por que cronograma e dignidade humana entram em tensao no jogo?",
    options: ["Recursos escassos criam trade-offs reais", "Toda escolha e neutra", "Nao ha consequencias", "Nao existe limite de tempo"],
    correctIndex: 0,
    explanation: "A proposta central e decisao moral com custo sistemico.",
  },
  {
    id: "q-14",
    category: "Trabalhadores",
    prompt: "No modo narrativo, moral baixa tende a causar:",
    options: ["Risco de motim e colapso social", "Aumento automatico de progresso", "Desbloqueio de final ideal", "Nenhum efeito"],
    correctIndex: 0,
    explanation: "Moral e pilar critico para estabilidade da operacao.",
  },
  {
    id: "q-15",
    category: "Doencas e Saneamento",
    prompt: "No jogo, saude sanitaria em colapso leva a:",
    options: ["Derrota por crise epidemiologica", "Bonus de prestigio", "Abertura de novo mapa", "Evento sem efeito"],
    correctIndex: 0,
    explanation: "A derrota sanitaria mantem o peso dramatico das decisoes.",
  },
  {
    id: "q-16",
    category: "Locomotivas",
    prompt: "Qual decisao preserva melhor a autenticidade de restauro?",
    options: ["Priorizar tecnica compativel com acervo", "Trocar todo sistema sem documentacao", "Pintar para parecer novo", "Ignorar oficina"],
    correctIndex: 0,
    explanation: "Restauro patrimonial exige documentacao e intervencao proporcional.",
  },
  {
    id: "q-17",
    category: "Patrimonio",
    prompt: "A Amazonia no jogo e tratada como:",
    options: ["Forca ambiental real do sistema", "Cenario estatico", "Filtro de cor", "Tema secundario"],
    correctIndex: 0,
    explanation: "Clima e territorio afetam recursos, risco e ritmo de jogo.",
  },
  {
    id: "q-18",
    category: "Tratado de Petropolis",
    prompt: "A narrativa do tratado conecta diplomacia e qual elemento logistico?",
    options: ["Integracao fluvial-ferroviaria", "Aviacao comercial", "Rede digital", "Gasoduto"],
    correctIndex: 0,
    explanation: "A ferrovia atuaria no elo logistico regional projetado no periodo.",
  },
  {
    id: "q-19",
    category: "Construcao",
    prompt: "Qual abordagem e mais fiel ao escopo V1?",
    options: ["Gestao leve com eventos decisorios", "Simulacao ferroviaria hardcore", "MMO com mercado global", "City builder de 366 km"],
    correctIndex: 0,
    explanation: "A V1 prioriza loop claro e modular.",
  },
  {
    id: "q-20",
    category: "Patrimonio",
    prompt: "Qual e o objetivo emocional do produto?",
    options: ["Reconstruir memoria com dignidade e escolha", "Somente acertar perguntas", "Focar em combate", "Colecionar moeda abstrata"],
    correctIndex: 0,
    explanation: "A experiencia combina patrimonio, decisoes e responsabilidade historica.",
  },
  {
    id: "q-21",
    category: "Tratado de Petropolis",
    prompt: "O tratado de 1903 envolveu principalmente Brasil e: ",
    options: ["Bolivia", "Peru", "Chile", "Paraguai"],
    correctIndex: 0,
    explanation: "A negociacao central foi entre Brasil e Bolivia.",
  },
  {
    id: "q-22",
    category: "Tratado de Petropolis",
    prompt: "No jogo, estudar tratados desbloqueia qual vantagem principal?",
    options: ["Contexto no codex e melhor leitura estrategica", "Vida extra automatica", "Combate mais forte", "Mapa 3D"],
    correctIndex: 0,
    explanation: "Conhecimento historico aumenta compreensao das consequencias.",
  },
  {
    id: "q-23",
    category: "Tratado de Petropolis",
    prompt: "A ferrovia aparece no contexto diplomatico como:",
    options: ["Instrumento de integracao e compromisso", "Tema sem relevancia", "Obra militar exclusiva", "Projeto urbano costeiro"],
    correctIndex: 0,
    explanation: "A obra conectava estrategia territorial e logistica.",
  },
  {
    id: "q-24",
    category: "Tratado de Petropolis",
    prompt: "Qual leitura o jogo privilegia sobre o tratado?",
    options: ["Diplomacia conectada a impactos humanos", "Apenas datas e nomes", "Somente dados economicos", "Somente biografias"],
    correctIndex: 0,
    explanation: "O foco e sistema historico com custo social.",
  },
  {
    id: "q-25",
    category: "Tratado de Petropolis",
    prompt: "Em termos de gameplay, acordos politicos no passado influenciam:",
    options: ["Os dilemas do presente no modo restauracao", "Somente a trilha sonora", "A velocidade do mouse", "Nada"],
    correctIndex: 0,
    explanation: "O produto conecta passado diplomatico e decisoes atuais.",
  },
  {
    id: "q-26",
    category: "Construcao",
    prompt: "No modo restauracao, eventos decisorios existem para:",
    options: ["Criar tensao entre metas concorrentes", "Preencher tela", "Trocar de mapa sem custo", "Eliminar escolha"],
    correctIndex: 0,
    explanation: "Eventos sao o motor do loop de gestao leve.",
  },
  {
    id: "q-27",
    category: "Construcao",
    prompt: "Qual ativo entra no ciclo inicial de restauro?",
    options: ["Oficina principal", "Aeroporto", "Frota maritima", "Terminal rodoviario"],
    correctIndex: 0,
    explanation: "A oficina e eixo tecnico da V1.",
  },
  {
    id: "q-28",
    category: "Construcao",
    prompt: "Quando o jogador prioriza velocidade sem manutencao adequada, tende a ocorrer:",
    options: ["Risco tecnico acumulado", "Bonus de preservacao", "Fim imediato positivo", "Sem impacto"],
    correctIndex: 0,
    explanation: "Decisao de curto prazo pode gerar crise posterior.",
  },
  {
    id: "q-29",
    category: "Construcao",
    prompt: "No design da V1, o calendario serve para:",
    options: ["Impor pressao de prazo", "Apenas decoracao", "Troca de idioma", "Desbloqueio de combate"],
    correctIndex: 0,
    explanation: "Prazo e pilar de tensao sistemica.",
  },
  {
    id: "q-30",
    category: "Construcao",
    prompt: "Qual risco de design foi explicitamente evitado?",
    options: ["Escopo de simulacao complexo demais", "Interface legivel", "Conteudo modular", "Save local"],
    correctIndex: 0,
    explanation: "A V1 evita virar simulador ferroviario hardcore.",
  },
  {
    id: "q-31",
    category: "Trabalhadores",
    prompt: "No arco narrativo, escolhas sobre liderancas de equipe afetam diretamente:",
    options: ["Moral e estabilidade do acampamento", "Qualidade do audio", "Tema do menu", "Latencia de rede"],
    correctIndex: 0,
    explanation: "Trabalho coletivo e legitimidade social sao centrais.",
  },
  {
    id: "q-32",
    category: "Trabalhadores",
    prompt: "Ignorar tensoes culturais no canteiro tende a:",
    options: ["Aumentar risco de ruptura", "Gerar bonus automatico", "Acelerar codex", "Reduzir custos sempre"],
    correctIndex: 0,
    explanation: "Conflitos ignorados retornam com maior custo.",
  },
  {
    id: "q-33",
    category: "Trabalhadores",
    prompt: "No jogo, reconhecer memoria de trabalhadores mortos pode:",
    options: ["Restaurar coesao social", "Eliminar todo risco", "Substituir manutencao", "Encerrar campanha"],
    correctIndex: 0,
    explanation: "Memorializacao tem efeito moral e simbolico.",
  },
  {
    id: "q-34",
    category: "Trabalhadores",
    prompt: "A principal fantasia do jogador inclui:",
    options: ["Ser agente ativo de decisoes historicas", "Apenas assistir cutscenes", "Competir em PvP", "Pilotar em tempo real"],
    correctIndex: 0,
    explanation: "A experiencia e centrada em decisao com consequencia.",
  },
  {
    id: "q-35",
    category: "Trabalhadores",
    prompt: "No modo historia, personagens jogaveis iniciais sao:",
    options: ["Trabalhador barbadiano e medico", "Engenheiro e prefeito", "Turista e guia", "Arqueologo e piloto"],
    correctIndex: 0,
    explanation: "Esses dois pontos de vista compoem a campanha curta da V1.",
  },
  {
    id: "q-36",
    category: "Doencas e Saneamento",
    prompt: "Uma decisao sanitaria dura pode prejudicar qual indicador de curto prazo?",
    options: ["Progresso tecnico", "Preservacao documental", "Codex desbloqueado", "Menu principal"],
    correctIndex: 0,
    explanation: "Saude e prazo entram em choque em varios eventos.",
  },
  {
    id: "q-37",
    category: "Doencas e Saneamento",
    prompt: "No capitulo do surto, deixar a triagem para depois tende a:",
    options: ["Elevar chance de agravamento", "Melhorar moral automaticamente", "Aumentar acertos no quiz", "Eliminar boatos"],
    correctIndex: 0,
    explanation: "Atraso sanitario amplifica risco epidemiologico.",
  },
  {
    id: "q-38",
    category: "Doencas e Saneamento",
    prompt: "No modelo do jogo, saude sanitaria e tratada como:",
    options: ["Recurso estrategico critico", "Tema secundario", "Decoracao de HUD", "Sistema opcional"],
    correctIndex: 0,
    explanation: "Colapso sanitario pode encerrar partidas.",
  },
  {
    id: "q-39",
    category: "Doencas e Saneamento",
    prompt: "Qual elemento ambiental piora doencas vetoriais no jogo?",
    options: ["Agua parada", "Alta velocidade do trem", "Noite limpa", "Arquivo seco"],
    correctIndex: 0,
    explanation: "Controle de agua e ponto recorrente de decisao.",
  },
  {
    id: "q-40",
    category: "Doencas e Saneamento",
    prompt: "A derrota por saude no modo narrativo ocorre quando:",
    options: ["Barra chega a zero", "Faltam perguntas", "Codex lota", "Mapa termina"],
    correctIndex: 0,
    explanation: "Zero em barra critica aciona game over.",
  },
  {
    id: "q-41",
    category: "Locomotivas",
    prompt: "A Locomotiva 50 no slice aparece como:",
    options: ["Ativo secundario de restauro", "Inimigo final", "Veiculo de quiz", "Asset removido"],
    correctIndex: 0,
    explanation: "Ela compoe o conjunto de ativos iniciais do projeto.",
  },
  {
    id: "q-42",
    category: "Locomotivas",
    prompt: "Qual leitura de restauro o jogo adota?",
    options: ["Tecnica + memoria + seguranca", "Somente estetica", "Somente velocidade", "Substituicao total"],
    correctIndex: 0,
    explanation: "A proposta evita restauro superficial.",
  },
  {
    id: "q-43",
    category: "Locomotivas",
    prompt: "No HUD de restauracao, progresso tecnico representa:",
    options: ["Capacidade de avancar tarefas de engenharia", "Apenas popularidade", "Som ambiente", "Qualidade do quiz"],
    correctIndex: 0,
    explanation: "E o indicador de operacao e entrega tecnica.",
  },
  {
    id: "q-44",
    category: "Locomotivas",
    prompt: "Uma falha em caldeira sugere qual postura de design?",
    options: ["Intervencao preventiva com custo", "Ignorar por ritmo", "Mudar paleta", "Trocar protagonista"],
    correctIndex: 0,
    explanation: "Decisoes preventivas sustentam longo prazo.",
  },
  {
    id: "q-45",
    category: "Locomotivas",
    prompt: "No jogo, locomotivas funcionam como:",
    options: ["Ativos patrimoniais e tecnicos", "Cosmeticos sem efeito", "Itens de combate", "NPCs"],
    correctIndex: 0,
    explanation: "Sao eixos de gestao e simbolo de memoria.",
  },
  {
    id: "q-46",
    category: "Patrimonio",
    prompt: "No design system, Papel Restauro e usado principalmente em:",
    options: ["Leitura narrativa e cards de codex", "Alerta critico", "HUD de crise", "Borda de erro"],
    correctIndex: 0,
    explanation: "A cor melhora conforto de leitura longa.",
  },
  {
    id: "q-47",
    category: "Patrimonio",
    prompt: "Qual cor funcional foi definida para perigo/crise?",
    options: ["#B64932", "#5E8A61", "#C59A5D", "#527A8A"],
    correctIndex: 0,
    explanation: "Vermelho ferrugem viva sinaliza risco critico.",
  },
  {
    id: "q-48",
    category: "Patrimonio",
    prompt: "O que o projeto evita explicitamente na arte?",
    options: ["Steampunk caricatural", "Tipografia serifada", "Contraste alto", "HUD modular"],
    correctIndex: 0,
    explanation: "A direcao busca sobriedade patrimonial, nao caricatura.",
  },
  {
    id: "q-49",
    category: "Patrimonio",
    prompt: "No metaloop, codex desbloqueado serve para:",
    options: ["Reforcar retencao e narrativa", "Substituir os modos", "Remover escolhas", "Resetar progresso"],
    correctIndex: 0,
    explanation: "Codex funciona como memoria ativa do jogador.",
  },
  {
    id: "q-50",
    category: "Patrimonio",
    prompt: "Qual definicao resume melhor o produto final?",
    options: ["Hub historico modular com gestao, narrativa e quiz", "Aplicativo de perguntas soltas", "Simulador militar", "Plataforma social"],
    correctIndex: 0,
    explanation: "A proposta integra patrimonio local, jogo e aprendizagem.",
  },
];
