import { getRestorationModuleImage } from "@/content/assetManifest";
import type { RestorationModule, RestorationTask } from "@/types/game";

export const restorationModules: RestorationModule[] = [
  {
    id: "trilhos",
    title: "Trilhos",
    kicker: "Modulo A",
    summary: "Trecho-piloto, drenagem, alinhamento e seguranca de circulacao para uso educativo.",
    objective: "Liberar um trecho demonstrativo com leitura patrimonial clara e risco controlado.",
    imageSrc: getRestorationModuleImage("trilhos"),
    subsystems: ["alinhamento", "lastro", "drenagem", "trecho-piloto"],
    taskIds: ["tri-diagnostico", "tri-restauro"],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao apoiada no uso turistico e educativo contemporaneo do complexo.",
    unlockSource: "restoration.trilhos",
  },
  {
    id: "barracoes",
    title: "Barracoes e Galpoes",
    kicker: "Modulo B",
    summary: "Cobertura, ventilacao, acessibilidade e adaptacao para uso museologico.",
    objective: "Transformar galpoes em suporte funcional para acervo, educacao e acolhimento.",
    imageSrc: getRestorationModuleImage("barracoes"),
    subsystems: ["cobertura", "iluminacao", "ventilacao", "acessibilidade"],
    taskIds: ["bar-diagnostico", "bar-restauro"],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel baseada na reativacao publica do conjunto em 2024.",
    unlockSource: "restoration.barracoes",
  },
  {
    id: "material-rodante",
    title: "Locomotiva e Material Rodante",
    kicker: "Modulo C",
    summary: "Locomotiva 18, litorina, oficina e exibicao operacional com conservacao preventiva.",
    objective: "Conectar restauro tecnico, exibicao segura e leitura publica do acervo rodante.",
    imageSrc: getRestorationModuleImage("material-rodante"),
    subsystems: ["locomotiva 18", "litorina", "oficina", "inspecao tecnica"],
    taskIds: ["rod-diagnostico", "rod-restauro"],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel apoiada nas exibicoes e passeios associados ao complexo.",
    unlockSource: "restoration.material-rodante",
  },
  {
    id: "operacao-publica",
    title: "Estruturas e Operacao",
    kicker: "Modulo D",
    summary: "Pontes, energia, sanitizacao, sinalizacao e operacao publica do complexo.",
    objective: "Amarrar seguranca operacional com experiencia de visitacao e leitura urbana.",
    imageSrc: getRestorationModuleImage("operacao-publica"),
    subsystems: ["pontes", "energia", "sanitizacao", "sinalizacao"],
    taskIds: ["ope-diagnostico", "ope-restauro"],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel para uma etapa de consolidacao da abertura ao publico.",
    unlockSource: "restoration.operacao-publica",
  },
];

export const restorationTasks: RestorationTask[] = [
  {
    id: "tri-diagnostico",
    moduleId: "trilhos",
    title: "Levantamento do trecho-piloto",
    summary: "Escolha o metodo de diagnostico do alinhamento, da drenagem e da seguranca de circulacao.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Define o escopo tecnico do trecho educativo.",
    risk: "Subestimar drenagem compromete liberacao futura.",
    dependencies: ["abertura do modulo trilhos"],
    evidenceType: "levantamento tecnico",
    choices: [
      {
        id: "tri-diagnostico-a",
        label: "Drone, georreferenciamento e vistoria de campo",
        summary: "Inspecao mais completa, com tempo de equipe maior.",
        outcome: "O diagnostico sustenta a priorizacao com dados confiaveis e reduz surpresas no trecho-piloto.",
        resourceDelta: { orcamento: -8, progressoTecnico: 10, preservacao: 8 },
        timelineNote: "Base tecnica consolidada para a priorizacao.",
      },
      {
        id: "tri-diagnostico-b",
        label: "Levantamento rapido focado em liberacao",
        summary: "Economiza tempo, mas deixa duvidas sobre drenagem e risco.",
        outcome: "A equipe ganha velocidade inicial, mas a confianca tecnica fica mais fragil.",
        resourceDelta: { orcamento: -3, progressoTecnico: 4, preservacao: -5, moral: -2 },
        timelineNote: "Escopo inicial avancou com maior risco residual.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao de rotina tecnica contemporanea baseada no uso publico atual do complexo.",
    unlockSource: "restoration.trilhos.diagnosis",
  },
  {
    id: "tri-restauro",
    moduleId: "trilhos",
    title: "Intervencao no trecho demonstrativo",
    summary: "Decida como equilibrar seguranca de uso, preservacao material e leitura educativa.",
    stage: "restoration",
    cost: "alto",
    time: "4 semanas",
    impact: "Condiciona a liberacao publica do trecho.",
    risk: "Solucao apressada reduz credibilidade do programa.",
    dependencies: ["tri-diagnostico"],
    evidenceType: "obra de conservacao",
    choices: [
      {
        id: "tri-restauro-a",
        label: "Restauro integral com sinalizacao interpretativa",
        summary: "Mais lento, mas fortalece seguranca e mediacao patrimonial.",
        outcome: "O trecho-piloto ganha leitura publica consistente e uso educativo mais robusto.",
        resourceDelta: { orcamento: -10, progressoTecnico: 7, preservacao: 10, moral: 4 },
        timelineNote: "Trecho-piloto preparado para validacao completa.",
      },
      {
        id: "tri-restauro-b",
        label: "Abertura parcial com estabilizacao minima",
        summary: "Entrega mais rapida para agenda publica imediata.",
        outcome: "A liberacao parcial funciona, mas a equipe registra limites tecnicos e educativos.",
        resourceDelta: { orcamento: -4, progressoTecnico: 5, preservacao: -6, moral: 2 },
        timelineNote: "Trecho-piloto segue para validacao com condicionantes.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel ligada ao uso turistico e educativo contemporaneo.",
    unlockSource: "restoration.trilhos.restoration",
  },
  {
    id: "bar-diagnostico",
    moduleId: "barracoes",
    title: "Mapa de umidade e acessibilidade",
    summary: "Defina se o primeiro ciclo prioriza cobertura e ventilacao ou acesso de publico.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Enquadra o uso museologico inicial dos galpoes.",
    risk: "Acessibilidade sem umidade controlada compromete o acervo.",
    dependencies: ["abertura do modulo barracoes"],
    evidenceType: "laudo integrado",
    choices: [
      {
        id: "bar-diagnostico-a",
        label: "Laudo integrado patrimonio + engenharia",
        summary: "Coordena cobertura, ventilacao e fluxo de visitantes na mesma leitura.",
        outcome: "A equipe passa a operar com prioridades mais coerentes entre acervo e recepcao publica.",
        resourceDelta: { orcamento: -7, preservacao: 8, progressoTecnico: 6, moral: 3 },
        timelineNote: "Diagnostico integrado aprovado para contratacao.",
      },
      {
        id: "bar-diagnostico-b",
        label: "Checklist rapido de uso expositivo",
        summary: "Agiliza o escopo de abertura, mas trata a umidade de forma secundaria.",
        outcome: "A agenda expositiva acelera, mas o risco de reincidencia sobre o acervo cresce.",
        resourceDelta: { orcamento: -3, progressoTecnico: 4, preservacao: -5 },
        timelineNote: "Diagnostico parcial aprovado com alertas.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel apoiada na reabertura e na funcao museologica do complexo.",
    unlockSource: "restoration.barracoes.diagnosis",
  },
  {
    id: "bar-restauro",
    moduleId: "barracoes",
    title: "Adaptacao dos galpoes para acervo e educacao",
    summary: "Escolha a estrategia para iluminar, ventilar e receber grupos com clareza patrimonial.",
    stage: "restoration",
    cost: "alto",
    time: "5 semanas",
    impact: "Determina a qualidade da experiencia editorial do hub museologico.",
    risk: "Excesso cenografico enfraquece o tom patrimonial.",
    dependencies: ["bar-diagnostico"],
    evidenceType: "intervencao de reuso",
    choices: [
      {
        id: "bar-restauro-a",
        label: "Reuso sobrio com iluminacao de leitura",
        summary: "Privilegia conforto ambiental e mediacao patrimonial.",
        outcome: "Os galpoes passam a apoiar visita, oficina educativa e leitura do acervo com mais coerencia.",
        resourceDelta: { orcamento: -9, preservacao: 9, moral: 5, progressoTecnico: 4 },
        timelineNote: "Espacos prontos para validacao de uso museologico.",
      },
      {
        id: "bar-restauro-b",
        label: "Abertura acelerada com ambientacao cenica",
        summary: "Entrega impacto imediato, mas reduz profundidade curatorial.",
        outcome: "O publico percebe a retomada, embora a equipe patrimonial registre concessoes no desenho expositivo.",
        resourceDelta: { orcamento: -5, progressoTecnico: 5, preservacao: -4, moral: 2 },
        timelineNote: "Espacos liberados com observacoes curatoriais.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel para consolidar o uso cultural ja documentado.",
    unlockSource: "restoration.barracoes.restoration",
  },
  {
    id: "rod-diagnostico",
    moduleId: "material-rodante",
    title: "Inspecao cruzada da Locomotiva 18 e da litorina",
    summary: "Defina se o foco inicial recai na seguranca operacional ou na exibicao publica imediata.",
    stage: "diagnosis",
    cost: "medio",
    time: "3 semanas",
    impact: "Enquadra a narrativa tecnica do material rodante.",
    risk: "Exibicao sem base tecnica enfraquece o programa.",
    dependencies: ["abertura do modulo material-rodante"],
    evidenceType: "inspecao mecanica",
    choices: [
      {
        id: "rod-diagnostico-a",
        label: "Inspecao de oficina com memoria material",
        summary: "Mapeia seguranca, autenticidade e uso expositivo do conjunto.",
        outcome: "A equipe ganha criterio para exibir a Locomotiva 18 com mais legitimidade tecnica.",
        resourceDelta: { orcamento: -8, progressoTecnico: 9, preservacao: 7 },
        timelineNote: "Diagnostico tecnico aprovado para contratacao especializada.",
      },
      {
        id: "rod-diagnostico-b",
        label: "Foco em exibicao rapida para o publico",
        summary: "Fortalece agenda cultural, mas deixa pendencias mecanicas abertas.",
        outcome: "A vitrine publica cresce primeiro e a oficina precisa correr atras da confiabilidade.",
        resourceDelta: { orcamento: -4, moral: 4, preservacao: -4, progressoTecnico: 3 },
        timelineNote: "Diagnostico parcial direcionado a exibicao imediata.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel apoiada nas exibicoes da Locomotiva 18 e nos passeios de litorina.",
    unlockSource: "restoration.material-rodante.diagnosis",
  },
  {
    id: "rod-restauro",
    moduleId: "material-rodante",
    title: "Plano de exibicao operacional",
    summary: "Escolha como equilibrar oficina aberta, manutencao preventiva e mediacao publica.",
    stage: "restoration",
    cost: "alto",
    time: "4 semanas",
    impact: "Molda o eixo mais simbolico do programa.",
    risk: "Superexpor o material rodante aumenta desgaste e expectativa publica.",
    dependencies: ["rod-diagnostico"],
    evidenceType: "conservacao preventiva",
    choices: [
      {
        id: "rod-restauro-a",
        label: "Oficina aberta com manutencao preventiva visivel",
        summary: "Transforma o restauro em experiencia educativa.",
        outcome: "A locomotiva e a litorina passam a comunicar processo, nao apenas resultado.",
        resourceDelta: { orcamento: -9, preservacao: 10, moral: 5, progressoTecnico: 6 },
        timelineNote: "Conjunto pronto para validacao publica controlada.",
      },
      {
        id: "rod-restauro-b",
        label: "Exibicao central com bastidor restrito",
        summary: "Valoriza o efeito de impacto e simplifica a operacao.",
        outcome: "A experiencia fica mais limpa para o visitante, mas menos transparente para o discurso do patrimonio.",
        resourceDelta: { orcamento: -5, moral: 4, preservacao: -3, progressoTecnico: 4 },
        timelineNote: "Exibicao montada com menor abertura de processo.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel associada a exibicoes e passeios contemporaneos do complexo.",
    unlockSource: "restoration.material-rodante.restoration",
  },
  {
    id: "ope-diagnostico",
    moduleId: "operacao-publica",
    title: "Mapa de energia, sinalizacao e visita",
    summary: "Defina o primeiro pacote de estrutura para operacao publica segura.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Organiza o ciclo de uso publico e equipes de apoio.",
    risk: "Sem leitura integrada, a visita perde seguranca e orientacao.",
    dependencies: ["abertura do modulo operacao-publica"],
    evidenceType: "auditoria operacional",
    choices: [
      {
        id: "ope-diagnostico-a",
        label: "Auditoria integrada de visita e manutencao",
        summary: "Cruza energia, fluxo de publico e resposta sanitaria.",
        outcome: "A operacao ganha um mapa mais confiavel para receber escola, turista e pesquisa.",
        resourceDelta: { orcamento: -6, moral: 4, saudeSanitaria: 6, progressoTecnico: 5 },
        timelineNote: "Prioridades operacionais validadas para contratacao.",
      },
      {
        id: "ope-diagnostico-b",
        label: "Plano minimo para abertura continuada",
        summary: "Foca na agenda publica sem aprofundar todos os sistemas.",
        outcome: "A visitacao segue mais rapidamente, mas as equipes operam com menos folga tecnica.",
        resourceDelta: { orcamento: -3, progressoTecnico: 3, saudeSanitaria: -4 },
        timelineNote: "Diagnostico minimo aprovado com alertas operacionais.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel baseada na abertura publica ja documentada.",
    unlockSource: "restoration.operacao-publica.diagnosis",
  },
  {
    id: "ope-restauro",
    moduleId: "operacao-publica",
    title: "Liberacao do circuito de visita",
    summary: "Escolha se a liberacao foca capacidade de agenda ou leitura patrimonial orientada.",
    stage: "restoration",
    cost: "alto",
    time: "3 semanas",
    impact: "Define a experiencia final da Entrega 1.",
    risk: "Capacidade sem mediacao clara esvazia o reposicionamento do produto.",
    dependencies: ["ope-diagnostico"],
    evidenceType: "plano de operacao",
    choices: [
      {
        id: "ope-restauro-a",
        label: "Circuito guiado com sinalizacao patrimonial",
        summary: "Entrega menos volume, mas mais contexto.",
        outcome: "O complexo passa a receber publico com narrativa mais coerente entre visita e memoria.",
        resourceDelta: { orcamento: -8, moral: 6, preservacao: 6, saudeSanitaria: 4 },
        timelineNote: "Circuito validado para liberacao publica assistida.",
      },
      {
        id: "ope-restauro-b",
        label: "Circuito amplo com operacao enxuta",
        summary: "Aumenta capacidade, mas deixa a mediacao em segundo plano.",
        outcome: "A agenda cresce, embora a profundidade editorial do percurso fique mais rasa.",
        resourceDelta: { orcamento: -4, progressoTecnico: 4, moral: 2, preservacao: -4 },
        timelineNote: "Circuito liberado com foco em fluxo e agenda.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel derivada da ativacao cultural e turistica documentada.",
    unlockSource: "restoration.operacao-publica.restoration",
  },
];

export const restorationModuleById = Object.fromEntries(restorationModules.map((item) => [item.id, item])) as Record<
  string,
  RestorationModule
>;

export const restorationTaskById = Object.fromEntries(restorationTasks.map((item) => [item.id, item])) as Record<string, RestorationTask>;
