import { getRestorationModuleImage } from "@/content/assetManifest";
import type { RestorationModule, RestorationTask } from "@/types/game";

export const restorationModules: RestorationModule[] = [
  {
    id: "trilhos",
    title: "Trilhos",
    kicker: "Modulo A",
    summary: "Trecho-piloto, drenagem, alinhamento e seguranca de circulacao para uso educativo.",
    objective: "Liberar um trecho demonstrativo com leitura patrimonial clara e risco controlado.",
    imageSrc: getRestorationModuleImage("trilhos"),
    subsystems: ["alinhamento", "lastro", "drenagem", "trecho-piloto"],
    taskIds: ["tri-diagnostico", "tri-priorizacao", "tri-contratacao", "tri-restauro", "tri-validacao"],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao apoiada no uso turistico e educativo contemporaneo do complexo.",
    unlockSource: "restoration.trilhos",
  },
  {
    id: "barracoes",
    title: "Barracoes e Galpoes",
    kicker: "Modulo B",
    summary: "Cobertura, ventilacao, acessibilidade e adaptacao para uso museologico.",
    objective: "Transformar galpoes em suporte funcional para acervo, educacao e acolhimento.",
    imageSrc: getRestorationModuleImage("barracoes"),
    subsystems: ["cobertura", "iluminacao", "ventilacao", "acessibilidade"],
    taskIds: ["bar-diagnostico", "bar-priorizacao", "bar-contratacao", "bar-restauro", "bar-validacao"],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel baseada na reativacao publica do conjunto em 2024.",
    unlockSource: "restoration.barracoes",
  },
  {
    id: "material-rodante",
    title: "Locomotiva e Material Rodante",
    kicker: "Modulo C",
    summary: "Locomotiva 18, litorina, oficina e exibicao operacional com conservacao preventiva.",
    objective: "Conectar restauro tecnico, exibicao segura e leitura publica do acervo rodante.",
    imageSrc: getRestorationModuleImage("material-rodante"),
    subsystems: ["locomotiva 18", "litorina", "oficina", "inspecao tecnica"],
    taskIds: ["rod-diagnostico", "rod-priorizacao", "rod-contratacao", "rod-restauro", "rod-validacao"],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel apoiada nas exibicoes e passeios associados ao complexo.",
    unlockSource: "restoration.material-rodante",
  },
  {
    id: "operacao-publica",
    title: "Estruturas e Operacao",
    kicker: "Modulo D",
    summary: "Pontes, energia, sanitizacao, sinalizacao e operacao publica do complexo.",
    objective: "Amarrar seguranca operacional com experiencia de visitacao e leitura urbana.",
    imageSrc: getRestorationModuleImage("operacao-publica"),
    subsystems: ["pontes", "energia", "sanitizacao", "sinalizacao"],
    taskIds: ["ope-diagnostico", "ope-priorizacao", "ope-contratacao", "ope-restauro", "ope-validacao"],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel para uma etapa de consolidacao da abertura ao publico.",
    unlockSource: "restoration.operacao-publica",
  },
];

export const restorationTasks: RestorationTask[] = [
  {
    id: "tri-diagnostico",
    moduleId: "trilhos",
    title: "Levantamento do trecho-piloto",
    summary: "Escolha o metodo de diagnostico do alinhamento, da drenagem e da seguranca de circulacao.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Define a confiabilidade do escopo tecnico.",
    risk: "Subestimar drenagem compromete a liberacao futura.",
    dependencies: ["abertura do modulo trilhos"],
    evidenceType: "levantamento tecnico",
    choices: [
      {
        id: "tri-diagnostico-a",
        label: "Drone, georreferenciamento e vistoria de campo",
        summary: "Inspecao mais completa, com tempo de equipe maior.",
        outcome: "O diagnostico sustenta a priorizacao com dados confiaveis e reduz surpresas no trecho-piloto.",
        resourceDelta: { orcamento: -8, progressoTecnico: 10, preservacao: 8 },
        timelineNote: "Base tecnica consolidada para a priorizacao.",
      },
      {
        id: "tri-diagnostico-b",
        label: "Levantamento rapido focado em liberacao",
        summary: "Economiza tempo, mas deixa duvidas sobre drenagem e risco.",
        outcome: "A equipe ganha velocidade inicial, mas a confianca tecnica fica mais fragil.",
        resourceDelta: { orcamento: -3, progressoTecnico: 4, preservacao: -5, moral: -2 },
        timelineNote: "Escopo inicial avancou com maior risco residual.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao de rotina tecnica contemporanea baseada no uso publico atual do complexo.",
    unlockSource: "restoration.trilhos.diagnosis",
  },
  {
    id: "tri-priorizacao",
    moduleId: "trilhos",
    title: "Definir o lote prioritario",
    summary: "Escolha como transformar o diagnostico em escopo visivel para a Entrega 1.",
    stage: "prioritization",
    cost: "medio",
    time: "1 semana",
    impact: "Define a narrativa tecnica do trecho liberado.",
    risk: "Escopo grande demais estoura prazo e caixa.",
    dependencies: ["tri-diagnostico"],
    evidenceType: "plano de escopo",
    choices: [
      {
        id: "tri-priorizacao-a",
        label: "Trecho curto, drenagem completa e sinalizacao base",
        summary: "Menor area, maior confiabilidade operacional.",
        outcome: "O plano privilegia seguranca e preservacao, com uma leitura patrimonial mais convincente.",
        resourceDelta: { orcamento: -5, preservacao: 7, progressoTecnico: 6 },
        timelineNote: "Priorizacao concentrou esforco em um lote controlado.",
      },
      {
        id: "tri-priorizacao-b",
        label: "Trecho maior para impacto publico imediato",
        summary: "Aumenta ambicao e visibilidade, mas espalha a equipe.",
        outcome: "A leitura publica cresce, embora o risco de pendencias tecnicas tambem aumente.",
        resourceDelta: { orcamento: -6, moral: 4, progressoTecnico: 4, preservacao: -4 },
        timelineNote: "Priorizacao ampliou o lote com maior exposicao ao risco.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de priorizacao tecnica para um trecho educativo.",
    unlockSource: "restoration.trilhos.prioritization",
  },
  {
    id: "tri-contratacao",
    moduleId: "trilhos",
    title: "Montar equipe, compra e cronograma",
    summary: "Escolha a forma de contratar e mobilizar a frente de obra.",
    stage: "contracting",
    cost: "alto",
    time: "2 semanas",
    impact: "Muda o equilibrio entre prazo, custo e controle de qualidade.",
    risk: "Contratacao apressada reduz confianca de execucao.",
    dependencies: ["tri-priorizacao"],
    evidenceType: "plano de mobilizacao",
    choices: [
      {
        id: "tri-contratacao-a",
        label: "Equipe especializada com cronograma escalonado",
        summary: "Mais cara, mas reduz retrabalho e melhora a governanca.",
        outcome: "A obra entra em campo com mais previsibilidade e melhor controle do risco tecnico.",
        resourceDelta: { orcamento: -9, progressoTecnico: 7, moral: 3 },
        timelineNote: "Mobilizacao especializada aprovada para execucao.",
      },
      {
        id: "tri-contratacao-b",
        label: "Pacote enxuto com equipe reduzida",
        summary: "Protege caixa no curto prazo, mas estressa a operacao.",
        outcome: "A contratacao economiza recursos, porem deixa menor margem para corrigir surpresas.",
        resourceDelta: { orcamento: -4, progressoTecnico: 3, moral: -4, saudeSanitaria: -2 },
        timelineNote: "Mobilizacao enxuta assumiu maior pressao operacional.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de contratacao para obra patrimonial de pequeno porte.",
    unlockSource: "restoration.trilhos.contracting",
  },
  {
    id: "tri-restauro",
    moduleId: "trilhos",
    title: "Intervencao no trecho demonstrativo",
    summary: "Decida como equilibrar seguranca de uso, preservacao material e leitura educativa.",
    stage: "restoration",
    cost: "alto",
    time: "4 semanas",
    impact: "Condiciona a liberacao publica do trecho.",
    risk: "Solucao apressada reduz credibilidade do programa.",
    dependencies: ["tri-contratacao"],
    evidenceType: "obra de conservacao",
    choices: [
      {
        id: "tri-restauro-a",
        label: "Restauro integral com sinalizacao interpretativa",
        summary: "Mais lento, mas fortalece seguranca e mediacao patrimonial.",
        outcome: "O trecho-piloto ganha leitura publica consistente e uso educativo mais robusto.",
        resourceDelta: { orcamento: -10, progressoTecnico: 7, preservacao: 10, moral: 4 },
        timelineNote: "Trecho-piloto preparado para validacao completa.",
      },
      {
        id: "tri-restauro-b",
        label: "Abertura parcial com estabilizacao minima",
        summary: "Entrega mais rapida para agenda publica imediata.",
        outcome: "A liberacao parcial funciona, mas a equipe registra limites tecnicos e educativos.",
        resourceDelta: { orcamento: -4, progressoTecnico: 5, preservacao: -6, moral: 2 },
        timelineNote: "Trecho-piloto segue para validacao com condicionantes.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel ligada ao uso turistico e educativo contemporaneo.",
    unlockSource: "restoration.trilhos.restoration",
  },
  {
    id: "tri-validacao",
    moduleId: "trilhos",
    title: "Validacao publica do trecho",
    summary: "Escolha a forma de abrir o trecho ao visitante sem perder leitura patrimonial.",
    stage: "validation",
    cost: "medio",
    time: "1 semana",
    impact: "Define como o publico percebe o valor do piloto.",
    risk: "Abrir sem mediacao suficiente banaliza a entrega.",
    dependencies: ["tri-restauro"],
    evidenceType: "comissionamento",
    choices: [
      {
        id: "tri-validacao-a",
        label: "Abertura assistida com mediacao e controle de carga",
        summary: "Menor capacidade, maior qualidade de leitura.",
        outcome: "O piloto estreia com seguranca, contexto e potencial de replicacao para a campanha.",
        resourceDelta: { moral: 5, preservacao: 4, progressoTecnico: 5 },
        timelineNote: "Trecho liberado com operacao assistida e leitura patrimonial clara.",
      },
      {
        id: "tri-validacao-b",
        label: "Abertura ampliada para ganhar tracao publica",
        summary: "Eleva visibilidade, mas pressiona a operacao logo na estreia.",
        outcome: "A campanha ganha volume inicial, embora o trecho estreie com menor controle de experiencia.",
        resourceDelta: { moral: 6, progressoTecnico: 3, preservacao: -4 },
        timelineNote: "Trecho liberado com foco em alcance publico imediato.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de abertura controlada ao publico.",
    unlockSource: "restoration.trilhos.validation",
  },
  {
    id: "bar-diagnostico",
    moduleId: "barracoes",
    title: "Mapa de umidade e acessibilidade",
    summary: "Defina se o primeiro ciclo prioriza cobertura e ventilacao ou acesso de publico.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Enquadra o uso museologico inicial dos galpoes.",
    risk: "Acessibilidade sem umidade controlada compromete o acervo.",
    dependencies: ["abertura do modulo barracoes"],
    evidenceType: "laudo integrado",
    choices: [
      {
        id: "bar-diagnostico-a",
        label: "Laudo integrado patrimonio + engenharia",
        summary: "Coordena cobertura, ventilacao e fluxo de visitantes na mesma leitura.",
        outcome: "A equipe passa a operar com prioridades mais coerentes entre acervo e recepcao publica.",
        resourceDelta: { orcamento: -7, preservacao: 8, progressoTecnico: 6, moral: 3 },
        timelineNote: "Diagnostico integrado aprovado para contratacao.",
      },
      {
        id: "bar-diagnostico-b",
        label: "Checklist rapido de uso expositivo",
        summary: "Agiliza o escopo de abertura, mas trata a umidade de forma secundaria.",
        outcome: "A agenda expositiva acelera, mas o risco de reincidencia sobre o acervo cresce.",
        resourceDelta: { orcamento: -3, progressoTecnico: 4, preservacao: -5 },
        timelineNote: "Diagnostico parcial aprovado com alertas.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel apoiada na reabertura e na funcao museologica do complexo.",
    unlockSource: "restoration.barracoes.diagnosis",
  },
  {
    id: "bar-priorizacao",
    moduleId: "barracoes",
    title: "Escolher o primeiro lote de adaptacao",
    summary: "Defina se o lote inicial serve melhor ao acervo ou ao fluxo de visita.",
    stage: "prioritization",
    cost: "medio",
    time: "1 semana",
    impact: "Orienta como o publico encontra o programa educativo.",
    risk: "Prioridade difusa gera entrega inconsistente.",
    dependencies: ["bar-diagnostico"],
    evidenceType: "plano curatorial",
    choices: [
      {
        id: "bar-priorizacao-a",
        label: "Ambiente-estudio para acervo e oficina educativa",
        summary: "Entrega menos impacto imediato, mas mais profundidade de uso.",
        outcome: "O galpao vira suporte forte para mediacao e trabalho com colecoes.",
        resourceDelta: { orcamento: -5, preservacao: 6, moral: 3 },
        timelineNote: "Lote inicial priorizou funcao educativa e de acervo.",
      },
      {
        id: "bar-priorizacao-b",
        label: "Recepcao ampliada e percurso de visita",
        summary: "Favorece acolhimento rapido, com menor densidade curatorial.",
        outcome: "A visita melhora cedo, mas parte do potencial pedagogico fica para depois.",
        resourceDelta: { orcamento: -4, moral: 4, preservacao: -2 },
        timelineNote: "Lote inicial privilegiou acolhimento e fluxo de visita.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel de definicao de escopo para reuso cultural.",
    unlockSource: "restoration.barracoes.prioritization",
  },
  {
    id: "bar-contratacao",
    moduleId: "barracoes",
    title: "Contratar execucao e mobiliario",
    summary: "Escolha o equilibrio entre customizacao patrimonial e entrega rapida.",
    stage: "contracting",
    cost: "alto",
    time: "2 semanas",
    impact: "Molda a qualidade final do reuso dos galpoes.",
    risk: "Padronizacao excessiva enfraquece a identidade do conjunto.",
    dependencies: ["bar-priorizacao"],
    evidenceType: "plano de fornecimento",
    choices: [
      {
        id: "bar-contratacao-a",
        label: "Fornecedores especializados em patrimonio",
        summary: "Mais caro, mas mais coerente com o tom do produto.",
        outcome: "A adaptacao respeita melhor materialidade, ventilacao e leitura do galpao.",
        resourceDelta: { orcamento: -8, preservacao: 7, progressoTecnico: 4 },
        timelineNote: "Contratacao especializada reforcou a coerencia patrimonial.",
      },
      {
        id: "bar-contratacao-b",
        label: "Pacote padrao de obra e mobiliario",
        summary: "Acelera entrega e simplifica compras.",
        outcome: "A obra fica mais previsivel, embora com menor refinamento de leitura patrimonial.",
        resourceDelta: { orcamento: -4, progressoTecnico: 3, preservacao: -3, moral: 1 },
        timelineNote: "Contratacao enxuta priorizou velocidade e padronizacao.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel de contratacao para adaptacao museologica.",
    unlockSource: "restoration.barracoes.contracting",
  },
  {
    id: "bar-restauro",
    moduleId: "barracoes",
    title: "Adaptacao dos galpoes para acervo e educacao",
    summary: "Escolha a estrategia para iluminar, ventilar e receber grupos com clareza patrimonial.",
    stage: "restoration",
    cost: "alto",
    time: "5 semanas",
    impact: "Determina a qualidade da experiencia editorial do hub museologico.",
    risk: "Excesso cenografico enfraquece o tom patrimonial.",
    dependencies: ["bar-contratacao"],
    evidenceType: "intervencao de reuso",
    choices: [
      {
        id: "bar-restauro-a",
        label: "Reuso sobrio com iluminacao de leitura",
        summary: "Privilegia conforto ambiental e mediacao patrimonial.",
        outcome: "Os galpoes passam a apoiar visita, oficina educativa e leitura do acervo com mais coerencia.",
        resourceDelta: { orcamento: -9, preservacao: 9, moral: 5, progressoTecnico: 4 },
        timelineNote: "Espacos prontos para validacao de uso museologico.",
      },
      {
        id: "bar-restauro-b",
        label: "Abertura acelerada com ambientacao cenica",
        summary: "Entrega impacto imediato, mas reduz profundidade curatorial.",
        outcome: "O publico percebe a retomada, embora a equipe patrimonial registre concessoes no desenho expositivo.",
        resourceDelta: { orcamento: -5, progressoTecnico: 5, preservacao: -4, moral: 2 },
        timelineNote: "Espacos liberados com observacoes curatoriais.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel para consolidar o uso cultural ja documentado.",
    unlockSource: "restoration.barracoes.restoration",
  },
  {
    id: "bar-validacao",
    moduleId: "barracoes",
    title: "Testar uso com grupos e mediadores",
    summary: "Defina como o galpao entra em operacao na primeira rodada publica.",
    stage: "validation",
    cost: "medio",
    time: "1 semana",
    impact: "Ajusta conforto, fluxo e leitura antes da estreia.",
    risk: "Validar pouco demais transfere problema para o visitante.",
    dependencies: ["bar-restauro"],
    evidenceType: "teste operacional",
    choices: [
      {
        id: "bar-validacao-a",
        label: "Piloto com escolas e equipe de mediacao",
        summary: "Menor escala, maior capacidade de ajuste fino.",
        outcome: "A equipe aprende com uso real e entra em abertura com mais seguranca.",
        resourceDelta: { moral: 4, preservacao: 3, progressoTecnico: 4 },
        timelineNote: "Galpao validado com piloto mediado e ajustes incorporados.",
      },
      {
        id: "bar-validacao-b",
        label: "Estreia direta na agenda cultural",
        summary: "Maximiza visibilidade, com menos tempo de correcao.",
        outcome: "O modulo estreia com mais tracao, embora alguns ajustes fiquem para depois da abertura.",
        resourceDelta: { moral: 5, progressoTecnico: 2, preservacao: -2 },
        timelineNote: "Galpao liberado direto para agenda cultural.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel de validacao para uso cultural inicial.",
    unlockSource: "restoration.barracoes.validation",
  },
  {
    id: "rod-diagnostico",
    moduleId: "material-rodante",
    title: "Inspecao cruzada da Locomotiva 18 e da litorina",
    summary: "Defina se o foco inicial recai na seguranca operacional ou na exibicao publica imediata.",
    stage: "diagnosis",
    cost: "medio",
    time: "3 semanas",
    impact: "Enquadra a narrativa tecnica do material rodante.",
    risk: "Exibicao sem base tecnica enfraquece o programa.",
    dependencies: ["abertura do modulo material-rodante"],
    evidenceType: "inspecao mecanica",
    choices: [
      {
        id: "rod-diagnostico-a",
        label: "Inspecao de oficina com memoria material",
        summary: "Mapeia seguranca, autenticidade e uso expositivo do conjunto.",
        outcome: "A equipe ganha criterio para exibir a Locomotiva 18 com mais legitimidade tecnica.",
        resourceDelta: { orcamento: -8, progressoTecnico: 9, preservacao: 7 },
        timelineNote: "Diagnostico tecnico aprovado para contratacao especializada.",
      },
      {
        id: "rod-diagnostico-b",
        label: "Foco em exibicao rapida para o publico",
        summary: "Fortalece agenda cultural, mas deixa pendencias mecanicas abertas.",
        outcome: "A vitrine publica cresce primeiro e a oficina precisa correr atras da confiabilidade.",
        resourceDelta: { orcamento: -4, moral: 4, preservacao: -4, progressoTecnico: 3 },
        timelineNote: "Diagnostico parcial direcionado a exibicao imediata.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel apoiada nas exibicoes da Locomotiva 18 e nos passeios de litorina.",
    unlockSource: "restoration.material-rodante.diagnosis",
  },
  {
    id: "rod-priorizacao",
    moduleId: "material-rodante",
    title: "Escolher o foco do primeiro ciclo",
    summary: "Defina se a primeira entrega privilegia oficina aberta ou vitrine central.",
    stage: "prioritization",
    cost: "medio",
    time: "1 semana",
    impact: "Molda a narrativa do material rodante na campanha.",
    risk: "Prioridade errada cria promessa dificil de sustentar.",
    dependencies: ["rod-diagnostico"],
    evidenceType: "escopo de exibicao",
    choices: [
      {
        id: "rod-priorizacao-a",
        label: "Processo de restauro como atracao",
        summary: "Menos brilho inicial, mais profundidade educativa.",
        outcome: "O modulo passa a valorizar o bastidor tecnico como parte do patrimonio vivo.",
        resourceDelta: { preservacao: 5, progressoTecnico: 5, moral: 2 },
        timelineNote: "Escopo priorizou processo tecnico e oficina aberta.",
      },
      {
        id: "rod-priorizacao-b",
        label: "Vitrine central para agenda e fotografia",
        summary: "Mais impacto imediato, menor visibilidade do processo.",
        outcome: "A campanha ganha uma imagem-farol mais rapida, com menos densidade de mediacao.",
        resourceDelta: { moral: 4, progressoTecnico: 3, preservacao: -2 },
        timelineNote: "Escopo priorizou impacto visual e agenda publica.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de priorizacao para exibicao rodante.",
    unlockSource: "restoration.material-rodante.prioritization",
  },
  {
    id: "rod-contratacao",
    moduleId: "material-rodante",
    title: "Contratar oficina e mediacao",
    summary: "Escolha o arranjo de equipe para operar restauro e visita.",
    stage: "contracting",
    cost: "alto",
    time: "2 semanas",
    impact: "Afeta a confianca do processo e a experiencia do visitante.",
    risk: "Equipe curta aumenta desgaste e improviso.",
    dependencies: ["rod-priorizacao"],
    evidenceType: "arranjo operacional",
    choices: [
      {
        id: "rod-contratacao-a",
        label: "Equipe mista de oficina e mediadores",
        summary: "Eleva custo, mas prepara uma experiencia mais solida.",
        outcome: "A manutencao preventiva conversa melhor com o discurso publico do modulo.",
        resourceDelta: { orcamento: -8, moral: 3, progressoTecnico: 5 },
        timelineNote: "Arranjo misto contratado para oficina e mediacao.",
      },
      {
        id: "rod-contratacao-b",
        label: "Equipe operacional enxuta",
        summary: "Protege caixa, mas concentra responsabilidade em poucos perfis.",
        outcome: "A operacao segue viavel, embora com menos folga para explicar o processo ao visitante.",
        resourceDelta: { orcamento: -4, progressoTecnico: 2, moral: -3 },
        timelineNote: "Arranjo enxuto contratado com menor redundancia.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de contratacao para oficina aberta e exibicao.",
    unlockSource: "restoration.material-rodante.contracting",
  },
  {
    id: "rod-restauro",
    moduleId: "material-rodante",
    title: "Plano de exibicao operacional",
    summary: "Escolha como equilibrar oficina aberta, manutencao preventiva e mediacao publica.",
    stage: "restoration",
    cost: "alto",
    time: "4 semanas",
    impact: "Molda o eixo mais simbolico do programa.",
    risk: "Superexpor o material rodante aumenta desgaste e expectativa publica.",
    dependencies: ["rod-contratacao"],
    evidenceType: "conservacao preventiva",
    choices: [
      {
        id: "rod-restauro-a",
        label: "Oficina aberta com manutencao preventiva visivel",
        summary: "Transforma o restauro em experiencia educativa.",
        outcome: "A locomotiva e a litorina passam a comunicar processo, nao apenas resultado.",
        resourceDelta: { orcamento: -9, preservacao: 10, moral: 5, progressoTecnico: 6 },
        timelineNote: "Conjunto pronto para validacao publica controlada.",
      },
      {
        id: "rod-restauro-b",
        label: "Exibicao central com bastidor restrito",
        summary: "Valoriza o efeito de impacto e simplifica a operacao.",
        outcome: "A experiencia fica mais limpa para o visitante, mas menos transparente para o discurso do patrimonio.",
        resourceDelta: { orcamento: -5, moral: 4, preservacao: -3, progressoTecnico: 4 },
        timelineNote: "Exibicao montada com menor abertura de processo.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel associada a exibicoes e passeios contemporaneos do complexo.",
    unlockSource: "restoration.material-rodante.restoration",
  },
  {
    id: "rod-validacao",
    moduleId: "material-rodante",
    title: "Abrir o modulo rodante ao publico",
    summary: "Defina a estreia publica do material rodante na campanha.",
    stage: "validation",
    cost: "medio",
    time: "1 semana",
    impact: "Fecha o modulo com impacto simbolico e tecnico.",
    risk: "Estreia sem mediacao clara gera leitura superficial.",
    dependencies: ["rod-restauro"],
    evidenceType: "abertura publica",
    choices: [
      {
        id: "rod-validacao-a",
        label: "Estreia guiada com narrativa de processo",
        summary: "Mais controlada, mais coerente com patrimonio vivo.",
        outcome: "O visitante entende como o restauro sustenta a ativacao contemporanea do complexo.",
        resourceDelta: { moral: 5, preservacao: 4, progressoTecnico: 4 },
        timelineNote: "Modulo rodante abriu com mediacao de processo e controle de visita.",
      },
      {
        id: "rod-validacao-b",
        label: "Estreia ampla focada em visibilidade",
        summary: "Aumenta o alcance inicial da entrega.",
        outcome: "A campanha ganha tracao publica, embora com menor densidade de interpretacao.",
        resourceDelta: { moral: 6, progressoTecnico: 2, preservacao: -2 },
        timelineNote: "Modulo rodante abriu com foco em alcance e agenda publica.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de abertura do acervo rodante a publico.",
    unlockSource: "restoration.material-rodante.validation",
  },
  {
    id: "ope-diagnostico",
    moduleId: "operacao-publica",
    title: "Mapa de energia, sinalizacao e visita",
    summary: "Defina o primeiro pacote de estrutura para operacao publica segura.",
    stage: "diagnosis",
    cost: "medio",
    time: "2 semanas",
    impact: "Organiza o ciclo de uso publico e equipes de apoio.",
    risk: "Sem leitura integrada, a visita perde seguranca e orientacao.",
    dependencies: ["abertura do modulo operacao-publica"],
    evidenceType: "auditoria operacional",
    choices: [
      {
        id: "ope-diagnostico-a",
        label: "Auditoria integrada de visita e manutencao",
        summary: "Cruza energia, fluxo de publico e resposta sanitaria.",
        outcome: "A operacao ganha um mapa mais confiavel para receber escola, turista e pesquisa.",
        resourceDelta: { orcamento: -6, moral: 4, saudeSanitaria: 6, progressoTecnico: 5 },
        timelineNote: "Prioridades operacionais validadas para contratacao.",
      },
      {
        id: "ope-diagnostico-b",
        label: "Plano minimo para abertura continuada",
        summary: "Foca na agenda publica sem aprofundar todos os sistemas.",
        outcome: "A visitacao segue mais rapidamente, mas as equipes operam com menos folga tecnica.",
        resourceDelta: { orcamento: -3, progressoTecnico: 3, saudeSanitaria: -4 },
        timelineNote: "Diagnostico minimo aprovado com alertas operacionais.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel baseada na abertura publica ja documentada.",
    unlockSource: "restoration.operacao-publica.diagnosis",
  },
  {
    id: "ope-priorizacao",
    moduleId: "operacao-publica",
    title: "Definir o circuito inicial",
    summary: "Escolha se o lote inicial prioriza orientacao do visitante ou robustez de bastidor.",
    stage: "prioritization",
    cost: "medio",
    time: "1 semana",
    impact: "Afeta clareza de visita e maturidade operacional.",
    risk: "Foco difuso gera uma abertura sem assinatura.",
    dependencies: ["ope-diagnostico"],
    evidenceType: "mapa de circuito",
    choices: [
      {
        id: "ope-priorizacao-a",
        label: "Circuito patrimonial guiado e bem sinalizado",
        summary: "Menor capacidade inicial, maior qualidade de leitura.",
        outcome: "O percurso fica mais coeso para escolas e visita mediada.",
        resourceDelta: { moral: 3, saudeSanitaria: 3, preservacao: 3 },
        timelineNote: "Prioridade concentrou o circuito em leitura e orientacao.",
      },
      {
        id: "ope-priorizacao-b",
        label: "Circuito amplo para absorver agenda",
        summary: "Aumenta capacidade, mas dilui o foco interpretativo.",
        outcome: "A operacao ganha folga de publico, com menos densidade de narrativa no percurso.",
        resourceDelta: { moral: 4, progressoTecnico: 2, preservacao: -2 },
        timelineNote: "Prioridade ampliou o circuito para absorver agenda.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel de definicao de percurso publico.",
    unlockSource: "restoration.operacao-publica.prioritization",
  },
  {
    id: "ope-contratacao",
    moduleId: "operacao-publica",
    title: "Amarrar turnos, sinalizacao e apoio",
    summary: "Escolha a estrategia de equipe e materiais para operacao da abertura.",
    stage: "contracting",
    cost: "alto",
    time: "2 semanas",
    impact: "Determina a estabilidade da rotina publica da campanha.",
    risk: "Equipe curta compromete manutencao e acolhimento.",
    dependencies: ["ope-priorizacao"],
    evidenceType: "plano de operacao",
    choices: [
      {
        id: "ope-contratacao-a",
        label: "Equipe ampliada com apoio de recepcao e manutencao",
        summary: "Mais robusta e mais cara.",
        outcome: "A abertura ganha maior confiabilidade para receber picos de visita e manter o percurso legivel.",
        resourceDelta: { orcamento: -7, moral: 4, saudeSanitaria: 4 },
        timelineNote: "Operacao reforcada foi contratada para a estreia.",
      },
      {
        id: "ope-contratacao-b",
        label: "Escala enxuta e sinalizacao essencial",
        summary: "Segura caixa, mas opera no limite.",
        outcome: "A abertura continua viavel, embora com menor margem para manutencao e resposta.",
        resourceDelta: { orcamento: -3, progressoTecnico: 2, moral: -3 },
        timelineNote: "Operacao enxuta assumiu menor redundancia de equipe.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "reopening-2024",
    confidenceNote: "Simulacao plausivel de contratacao para abertura publica.",
    unlockSource: "restoration.operacao-publica.contracting",
  },
  {
    id: "ope-restauro",
    moduleId: "operacao-publica",
    title: "Liberacao do circuito de visita",
    summary: "Escolha se a liberacao foca capacidade de agenda ou leitura patrimonial orientada.",
    stage: "restoration",
    cost: "alto",
    time: "3 semanas",
    impact: "Define a experiencia final da Entrega 1.",
    risk: "Capacidade sem mediacao clara esvazia o reposicionamento do produto.",
    dependencies: ["ope-contratacao"],
    evidenceType: "plano de operacao",
    choices: [
      {
        id: "ope-restauro-a",
        label: "Circuito guiado com sinalizacao patrimonial",
        summary: "Entrega menos volume, mas mais contexto.",
        outcome: "O complexo passa a receber publico com narrativa mais coerente entre visita e memoria.",
        resourceDelta: { orcamento: -8, moral: 6, preservacao: 6, saudeSanitaria: 4 },
        timelineNote: "Circuito validado para liberacao publica assistida.",
      },
      {
        id: "ope-restauro-b",
        label: "Circuito amplo com operacao enxuta",
        summary: "Aumenta capacidade, mas deixa a mediacao em segundo plano.",
        outcome: "A agenda cresce, embora a profundidade editorial do percurso fique mais rasa.",
        resourceDelta: { orcamento: -4, progressoTecnico: 4, moral: 2, preservacao: -4 },
        timelineNote: "Circuito liberado com foco em fluxo e agenda.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel derivada da ativacao cultural e turistica documentada.",
    unlockSource: "restoration.operacao-publica.restoration",
  },
  {
    id: "ope-validacao",
    moduleId: "operacao-publica",
    title: "Fechar o protocolo da abertura",
    summary: "Defina o rito final de estreia da EFMM 2026.",
    stage: "validation",
    cost: "medio",
    time: "1 semana",
    impact: "Consolida a leitura final da campanha.",
    risk: "Abrir cedo demais expoe fragilidades acumuladas.",
    dependencies: ["ope-restauro"],
    evidenceType: "protocolo de estreia",
    choices: [
      {
        id: "ope-validacao-a",
        label: "Abertura faseada com ajustes monitorados",
        summary: "Mais prudente e mais madura para consolidar a operacao.",
        outcome: "A entrega finaliza com leitura forte de cuidado, patrimonio e continuidade.",
        resourceDelta: { moral: 4, saudeSanitaria: 3, preservacao: 3, progressoTecnico: 3 },
        timelineNote: "Abertura faseada consolidou a operacao com monitoramento.",
      },
      {
        id: "ope-validacao-b",
        label: "Abertura integral para marcar a reativacao",
        summary: "Amplia alcance e simbolismo da entrega final.",
        outcome: "O fechamento da campanha ganha impacto, embora com menor tempo para calibrar a rotina.",
        resourceDelta: { moral: 6, progressoTecnico: 2, saudeSanitaria: -2 },
        timelineNote: "Abertura integral marcou a reativacao com maior exposicao operacional.",
      },
    ],
    contentType: "simulation_2026",
    sourceRef: "activation-2025-2026",
    confidenceNote: "Simulacao plausivel de protocolo final de abertura publica.",
    unlockSource: "restoration.operacao-publica.validation",
  },
];

export const restorationModuleById = Object.fromEntries(restorationModules.map((item) => [item.id, item])) as Record<
  string,
  RestorationModule
>;

export const restorationTaskById = Object.fromEntries(restorationTasks.map((item) => [item.id, item])) as Record<string, RestorationTask>;
